### PR TITLE
Fix RTL for combobox

### LINKED ISSUE #1045: Combobox: support RTL
Unlike most of the other components, it looks like combobox is not displaying correctly when set to RTL (in this screenshot I quickly updated the default example to be RTL):

Screen Shot 2020-03-06 at 10 19 01 AM

HINT: icon should be at far left, text at far right.

Not investigated fully, but lets see if it can be fixed in a backwards compatible manner. If not, we'll have to wait till v11.

### PR DESCRIPTION
**Pull request by raveenakothapally**
PLEASE SQUASH.

Fixes #1045

Because combobox uses absolute positioning for dropdown icon, RTL feature is broken. This PR adds CSS to RTL direction combobox that adjusts the placement of icon and text box.

Kapture 2020-03-25 at 12 27 04

### CODE REVIEW

**Comment by ianmcburnie** [comment]
So, typically the way RTL works is that it is inherited in the cascade (and is based on system language preferences). We would not ask that developers apply the `dir` attribute directly within our module. A way to test this is by wrapping the module in a div with dir=rtl.

**Comment by raveenakothapally** [comment]
> So, typically the way RTL works is that it is inherited in the cascade (and is based on system language preferences). We would not ask that developers apply the `dir` attribute directly within our module. A better way to test this is by wrapping the module in a div with `dir="rtl"`.

That is true, I just updated the PR accordingly.

**Comment by ianmcburnie** [comment]
I ran into a few lint errors when trying to run:

Screen Shot 2020-03-27 at 1 10 43 PM

This reminds me, we should probably add a hook to do linting before every commit or push.

**Comment by ianmcburnie** [comment]
I would also expect the text to be aligned to the right, like it is in textbox RTL test case:

Screen Shot 2020-03-28 at 12 14 12 PM

**Comment by ianmcburnie** [comment]
@raveenakothapally I added a commit which addresses some issues. The only remaining issue I see is the actionable RTL test case. I added a new hook `combobox__control--actionable` that I think will be needed. See if you can fix that test case. If not, I think it's an edge case that can stay broken until we refactor combobox as a whole in v11.

**Comment by raveenakothapally** [comment]
> @raveenakothapally I added a commit which addresses some issues. The only remaining issue I see is the actionable RTL test case. I added a new hook `combobox__control--actionable` that I think will be needed. See if you can fix that test case. If not, I think it's an edge case that can stay broken until we refactor combobox as a whole in v11.

I did not quite get the reason for `combobox__control--actionable`.

I updated the styles and added test case for actionable combobox RTL. Please let me know if it looks good.

**Pull request merged**
