### PR TITLE
fix padding on input in combobox to allow for icon

### PR DESCRIPTION
**Pull request by msendlakowski**
## Description
Adding padding and ellipses to comobobox text element

## Context
fixes https://github.com/eBay/ebayui-core/issues/224

## Screenshots
screen shot 2018-08-21 at 1 30 43 pm

screen shot 2018-08-21 at 1 31 09 pm

### CODE REVIEW

**Comment by seangates** [comment]
I'm seeing an interesting issue when you focus on the combobox now:

combobox focus issue

**Comment by seangates** [comment]
I'm not entirely sure how to fix it yet.

**Comment by msendlakowski** [comment]
Yeah. I saw that.  I don't know if there is a fix, other than allowing the long content to extend the input field.  

We could hide the icon when the field has focus, but I think that would be more distracting.  Any other ideas?

**Comment by seangates** [comment]
I think this goes back to the the read-only `<input>` as part of this `combobox`, and the weird behaviors we're seeing across the board. Let's not worry about it for now.

**Comment by msendlakowski** [comment]
Closing this for now.  I'll put the issue in the backlog and reference this PR for a future fix if needed.

**Pull request closed without merging**
