### PR TITLE
Fix combobox because of makeup-expander changes;

### PR DESCRIPTION
**Pull request by seangates**
## Description
- fix selector for descendant to be expanded

## Context
New changes to `makeup-expander` now allow for any number of nested elements between the root of the expander and both the expander host and the expander content. This change allows the markup to be more flexible. Specifically, we identified the limitations of the previous selector when attempting to build the tooltip with reusable Marko components which required multiple level nesting of the host and content under the root expander.

## References
https://github.com/eBay/ebayui-core/pull/499
https://github.com/makeup-js/makeup-expander/pull/9

### CODE REVIEW

**Comment by seangates** [comment]
@ianmcburnie Yes, we will want to publish this and propagate the new version number to eBayUI before that PR is merged.

**Comment by ianmcburnie** [comment]
I was talking about the Skin website, but I forget that it hasn't been updated to use makeup-expander yet. Instead, as a temporary fix, I think you'll need to update `main.js` with the new class.

**Comment by seangates** [comment]
@ianmcburnie I misspoke: this doesn't need expander to be updated, since `devDependencies` will pick up the most recent patch version.

**Comment by seangates** [comment]
_Ignore my interim comment. It wasn't correct given the breaking change in the expander would be _minor_ version and not a patch._

Yes, I need to update the Skin docs to add the `expandedClass` in the examples which need it. e.g. Combobox.

**Comment by ianmcburnie** [comment]
Oh wait. I approved this before you updated the js. Oops.

**Comment by seangates** [comment]
@ianmcburnie It's now updated.

**Comment by seangates** [comment]
@ianmcburnie Whoops. Your review just got dismissed, @ianmcburnie. Not sure what I did, other than resolving the conflicts with the generated CSS files.

**Pull request merged**
