### PR TITLE
Actionable: Fix icon width

### PR DESCRIPTION
**Pull request by seangates**
## Description
- add `width: 100%;` to SVG in the actionable button
- fix base actionable button height/width to 40px
- normalize actionable height/width between `<button>` and `<a>` types

## Context
The actionable button SVG width was causing a weird overflow to happen. Also, the default sizewas not normalized correctly, making the actionable anchor version slightly larger than the button version.

## References
#905 

### Before

image

image

### After

image

image

### CODE REVIEW

**Comment by LokeshRishi** [comment]
@seangates Does this fix apply to all `ebay-tooltip` icons?
For instance: https://ebay.github.io/ebayui-core/?path=/story/ebay-tooltip--icon-button-host

**Comment by seangates** [comment]
@LokeshRishi Yes, this should apply to all the tooltip/infotip/tourtip icons. `actionable` is a base set of classes for them.

**Comment by ianmcburnie** [comment]
@seangates I'm just looking at this again. I like the uniformity/symmetry of the icon button after this update, and the reduced padding, but it looks on the large side now. I'm just wondering where 40px x 40px came from. I'm not seeing it in the playbook. This *may* also be considered a breaking change. Thoughts? Should we keep the changes, but drop the size down a little?

Before

Screen Shot 2019-11-11 at 8 17 44 PM

After

Screen Shot 2019-11-11 at 8 17 37 PM

**Comment by seangates** [comment]
@ianmcburnie In essence, I just normalized the button size, and updated the SVG rule to let the icon stretch to it's normal size. Removing the `width: 100%` is probably okay. Or, even, changing it to `max-width: 16px` (or something reasonable)?

The `height: 40px` (and making `width: 40px;`) follows the sizing height of buttons in general across the Design System. Having it be 2px taller was ... odd to me.

**Comment by ianmcburnie** [comment]
@seangates Thanks for the info. In order for this not to be too jarring for people upgrading their minor version, I'm thinking of dropping width and height from 100% to 60% or so.

Currently in this branch:

Screen Shot 2019-11-12 at 10 57 28 AM

Currently in production:

Screen Shot 2019-11-12 at 10 56 46 AM

Proposed (this is 60%, but looks like I need a smidgen higher):

Screen Shot 2019-11-12 at 10 57 41 AM

**Comment by ianmcburnie** [comment]
Just realised that reducing to 60% has a knock on effect in other places, like infotip, so I'd need to add an override or rethink this.

Screen Shot 2019-11-12 at 11 55 50 AM

**Comment by ianmcburnie** [comment]
@seangates Related to previous comment, looks like your PR also affected badge, and maybe some other places too.

Before

Screen Shot 2019-11-12 at 12 13 20 PM

After

Screen Shot 2019-11-12 at 12 13 28 PM

**Comment by seangates** [comment]
@ianmcburnie Okay. Let me have a look later today when I have a free moment. Thanks for letting me know the downstream affects here.

**Comment by ianmcburnie** [comment]
Thanks. A search for `icon-btn` in `docs` folder shows the downstream use cases:

* badge
* section-title
* tooltip

**Pull request merged**
