### PR TITLE
Combobox: support an editable version

### PR DESCRIPTION
**Pull request by seangates**
## Description
- remove text shadow "magic"
- reinstate the text highlighting
- reinstate the cursor
- backwards compatibility read-only combobox (present version)

## Context
Adding an editable combobox.

## References
eBayUI Core issue: https://github.com/eBay/ebayui-core/issues/22

## Screenshots
image

### CODE REVIEW

**Comment by seangates** [comment]
Where did I get `--focussed` then? 🤔

**Comment by seangates** [comment]
@ianmcburnie Updated. Please review once more.

**Comment by ianmcburnie** [comment]
I'm not seeing the new styles on the editable combobox:

Screen Shot 2019-04-02 at 8 50 16 AM

Only the readonly combobox:

Screen Shot 2019-04-02 at 8 50 29 AM

**Comment by seangates** [comment]
I just now fixed a selector. Please check again.

**Comment by ianmcburnie** [comment]
@seangates I see a light gray background keyboard state has been added for ds4, but it's not showing up on mouse hover like on ds6.

**Comment by seangates** [comment]
@ianmcburnie My intention was not to make any additional commits, but I spotted a couple of errors, and therefore fixed them.

**Comment by seangates** [comment]
@ianmcburnie Hover fixed.

**Pull request merged**
