### PR TITLE
Bolder icons for menu, combobox, and select

### LINKED ISSUE #79: Update menu icons with new "bolder" stroke versions
So as not to block #78 (new dropdown patterns), we are creating this issue to track updating the dropdown arrow and selected check mark, since they have become more bold (e.g. a heavier stroke weight) to match the heavier font changes in #78.

### PR DESCRIPTION
**Pull request by seangates**
## Description
To align with DS6 design, we need to use a slightly bolder version of the carets.

## References
Closes #79 

## Screenshots

**Before**
image

**After**
image

### CODE REVIEW

**Comment by ianmcburnie** [comment]
@seangates Does this also update the checkmark? Do you mind adding a screenshot of before and after, just so we can visualize the change.

**Comment by seangates** [comment]
@ianmcburnie There is no bold version of the tick mark.

**Comment by seangates** [comment]
@ianmcburnie Although, I did make a slight change to the tick mark, as it did not match the width of the chevron.

**Comment by seangates** [comment]
@ianmcburnie I added screen shots.

BTW, their "weight" gain is miniscule. The icons used in the DSL dropdown page don't help, either, because they are not the correct chevrons. We should eventually have a review with platform design.

**Pull request merged**
