### PR TITLE
Force maximum height for menu and combobox items, with scroll;

### LINKED ISSUE #335: Combobox: when there are many options - When expanded, there is no scroll inside the component. It scrolls with the page
Moving from: https://github.com/eBay/ebayui-core/issues/228

# Bug Report

## Description
when there are many options - When expanded, there is no scroll inside the componenet. It scrolls with the page

repro:
https://go/ebayui/test2
go to ebay-combobox nested - too many options - scroll
expand it

Issue: it scrolls with the page.
There is no scroll bar inside the component

https://www.useloom.com/share/49d0bea18e9d4d6987acebba68d09817

### PR DESCRIPTION
**Pull request by seangates**
## Description
- adds CSS to limit height of the menu/combobox (dropdown) items
- adds examples of the scrollable versions

## Context
The Design System states that the limit is **ten** and should be scrollable thereafter. Given that each of the components are 38px high, we set it at 10 * 40px and **peek the eleventh**.

## References
Fixes #335 

## Screenshots

**Before**

image

**After**

image

### CODE REVIEW

**Comment by seangates** [comment]
@msendlakowski Yes, I think this is not about the size of the items, but more the container itself. Really, if it's 200%, that's still 5+ items in the list.

**Comment by msendlakowski** [comment]
Found one other issue.  But I don't know if its solvable with CSS.
If you use the keyboard to scroll down the list, the container doesn't scroll once you get out of the visible area.  We probably need JS to keep the items visible.

**Comment by seangates** [comment]
@msendlakowski Yes, it would need JS code to do that, unfortunately.

I could do that in this PR, for the Skin docs. Let me take a stab at it, but I don't want to hold up the first part of this change.

Could you make an issue in `ebayui-core` to do this on the components' side?

**Comment by seangates** [comment]
@msendlakowski Got the "scroll into view" to work for the docs.

**Comment by ianmcburnie** [comment]
@seangates I only see changes to DS6 css, not DS4. Is there a reason these changes were only made for DS6? We should be keeping DS4 and DS6 in sync.

**Pull request merged**
