### PR TITLE
Add align-items to snackbar window class

### PR DESCRIPTION
**Pull request by austingardner**
## Description
Just adds align-items into the snackbar-window class. This is necessary because using the ebay-button in ebay-ui in the snackbar-dialog misaligned the text with the button. 

No visual changes in skin, the screenshots are for the issue in ebay-UI. (Currently skin is using a button here and doesn't have the same CSS that the ebay-button has)

## References
[snackbar dialog ebay-ui PR](https://github.com/eBay/ebayui-core/pull/1338)

## Screenshots 
Before (ebay-UI with ebay-button)
Screen Shot 2021-02-26 at 9 46 41 AM

After (adding align-items to snackbar window class)
Screen Shot 2021-02-26 at 11 44 55 AM

### CODE REVIEW

**Comment by ianmcburnie** [comment]
In these types of PRs can you add a screenshot of before and after? I'm not sure what is broken:

Screen Shot 2021-02-26 at 10 48 39 AM

**Comment by austingardner** [comment]
added screenshots to describe issue.

**Comment by ianmcburnie** [comment]
Everything looks fine on the skin side, so this might be a class mismatch. Can you recheck all of the classes that are being added in coreui. It should be using the fake link variant, and adding `snackbar-dialog__cta`.

Here's how it should render:

```html
<button accesskey="u" class="fake-link snackbar-dialog__cta">Undo<span class="clipped"> - Access Key: U</span></button>
```

**Comment by austingardner** [comment]
``` html
<button class="fake-link snackbar-dialog__cta btn btn--secondary" data-ebayui="" type="button">Undo<span class="clipped"> - Access Key: U</span></button>
```

here's how it is rendering. So you're saying it shouldn't have the btn and btn--secondary classes?

**Comment by ianmcburnie** [comment]
Correct. Are you using the `fake-link` variant? If so, there could be a bug with the fake link logic.

**Comment by austingardner** [comment]
oh whoops. I wasn't using a variant, I was just putting on the `fake-link snackbar-dialog__cta` as the class of the ebay-button. 

When I changed it I didn't do it correctly. 

Closing PR!

**Pull request closed without merging**
