### PR TITLE
Removed unnecessary nesting in storybook

### PR DESCRIPTION
**Pull request by LuLaValva**
- [ ] This PR contains CSS changes
- [x] This PR does not contain CSS changes

## Description

Many of the entries in the storybook for Skin contain nesting that may be considered as unnecessary. This PR removes the nesting in each of these circumstances.

## Screenshots

Before:
image
After:
image

## Checklist

- [x] I verify the build is in a non-broken state
- [x] I verify all changes are within scope of the linked issue

- [ ] I regenerated all CSS files under dist folder
- [ ] I tested the UI in all supported browsers
- [ ] I tested the UI in dark mode and RTL mode
- [x] I added/updated/removed Storybook coverage as appropriate

### CODE REVIEW

**Comment by ianmcburnie** [comment]
Seems like the branch needs rebasing with 14.1.0

**Review by ianmcburnie — DISMISSED** [review]

**Review by agliga — APPROVED** [review]

**Comment by agliga** [comment]
Lets get all the merge conflicts resolved and merge this into master

**Review by ArtBlue — COMMENTED** [review]
It looks great overall. The only oddity (small thing) is the top-level module icon differences...

image

The icon for alert dialog and badge are different from breadcrumbs, buttons...

I can't see any differences between those. Any idea why and how to make them consistent?

**Comment by LuLaValva** [comment]
> It looks great overall. The only oddity (small thing) is the top-level module icon differences...

The line between component and directory is kind of blurry in storybook, since they are only calculated for display purposes based on titles. Under the hood, `Buttons` and `Cascade` function in the same manner but since `Buttons` has more than one layer of stories when it is expanded it is displayed with a folder icon.

We can "fix" this by rethinking how we organize components. If you'd like, I can perform a similar refactor to this storybook as I did for `ebay-ui`.

**Comment by ArtBlue** [comment]
> We can "fix" this by rethinking how we organize components. If you'd like, I can perform a similar refactor to this storybook as I did for `ebay-ui`.

I like the idea. Let's do it. Thanks for the suggestion.

**Comment by LuLaValva** [comment]
Update: After some more discussion, @ArtBlue and I decided that since the `skin` components do not cleanly fit into the same categories as those in `ebayui` and nesting seems to be necessary in certain cases we are going to refrain from adding categories for now.

**Review by ArtBlue — APPROVED** [review]
Looks good!

**Comment by ArtBlue** [comment]
Nice work, @LuLaValva !

**Pull request merged**
