### PR TITLE
feat(section-title): updated section titles to match new specs

### LINKED ISSUE #1728: section-title: updated "see all" variant
The section title component is being updated to replace the arrow icon button with a link button pinned to the right of the screen. The button defaults to have a label of "See all".
DOD: Section title styling has been updated to match Playbook specs.

[Figma component](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/?node-id=54324%3A83599)

[Playbook page](https://playbook.corp.ebay.com/PlaybookApp#/executional-guidelines/product-design-system/patterns/section-titles)

image-2022-04-20-11-05-09-499
image-2022-04-20-11-05-23-562
image-2022-04-20-11-05-36-464
image-2022-04-20-11-05-47-464
image-2022-04-20-11-05-55-564

### PR DESCRIPTION
**Pull request by ArtBlue**
Fixes #1728 

- [x] This PR contains CSS changes
- [ ] This PR does not contain CSS changes

## Description
Updates to the section title component to match new specs.

### Breaking Changes

* `<div class="section-title__cta">` that contained an anchor `<a href="https://www.ebay.com" tabindex="-1" aria-hidden="true"><span class="section-title__cta-text">See All</span>` has been simplified to this:

`<a class="section-title__cta" href="https://www.ebay.com">Link</a>`

The link is now an element promoted to a first-level child in the component.

### Additional (necessary) Changes

*Token Reference Changes*
* `--color-foreground-secondary` > `--color-neutral-4` > #8f8f8f
* `--color-background-primary` > `--color-neutral-8` > #000

*Dark Mode Background Change*
* As a result of `--color-background-primary` change, dark mode page background color has now been changed to pure black (`#000`).

## Screenshots
There are many changes across the board on all the variations of the component. This is just one of those changes.

Before:
image

After:
image

## Checklist

- [x] I verify the build is in a non-broken state
- [ ] I verify all changes are within scope of the linked issue

- [x] I regenerated all CSS files under dist folder
- [x] I tested the UI in all supported browsers
- [x] I tested the UI in dark mode and RTL mode
- [x] I added/updated/removed Storybook coverage as appropriate

### CODE REVIEW

**Review by agliga — APPROVED** [review]
Tried it locally, I like that the code has been cleaned up. 
Looks good to me.
Only issue I saw was some icons were not aligned, but it matches figma, so it's fine imo.
Screen Shot 2022-09-12 at 7 27 03 PM

**Comment by ArtBlue** [comment]
> Tried it locally, I like that the code has been cleaned up. Looks good to me. Only issue I saw was some icons were not aligned, but it matches figma, so it's fine imo. Screen Shot 2022-09-12 at 7 27 03 PM

I'll take care of it; it does look a bit off. This should be better.

image

**Review by LuLaValva — CHANGES_REQUESTED** [review]
I'm not sure of the other impacts, but I think with the background-primary change it makes sense to also change evo-dark `--color-background-secondary` to `--color-neutral-7`. I noticed this mostly on textboxes, but this change will require us to look through all components using background-secondary.

**Comment by ArtBlue** [comment]
> I'm not sure of the other impacts, but I think with the background-primary change it makes sense to also change evo-dark `--color-background-secondary` to `--color-neutral-7`. I noticed this mostly on textboxes, but this change will require us to look through all components using background-secondary.

So, according to Randy, `--color-background-primary` should have been using `--color-neutral-8`. He was surprised it wasn't and is aware the change will proliferate. I didn't see anything weird with textboxes. Can you post what you're seeing? I'd like very much to keep the rest of this issue concentrated on just the issue (and what is necessary for it).

I suppose if it looks bad enough, maybe we can consider more revisions, but those should probably be done in another issue anyway. It can also easily be patched if Randy agrees to the change.

**Comment by rbascue** [comment]
Yes, that is correct. `--color-background-primary` should reference `--color-neutral-8`.
And `--color-background-secondary` should reference `--color-neutral-7`.

**Comment by rbascue** [comment]
image

**Comment by rbascue** [comment]
image

**Review by LuLaValva — APPROVED** [review]

**Pull request merged**
