### PR TITLE
v16.0.0 Release

### PR DESCRIPTION
**Pull request by ArtBlue**
PR for `16.0.0` release.

### CODE REVIEW

**Review by saiponnada — COMMENTED** [review]
Looked at my changes and skimmed the site.  Overall looks good to me.

**Review by agliga — APPROVED** [review]

**Comment by ianmcburnie** [comment]
I'm going to make a few small edits to the docs.

**Comment by ianmcburnie** [comment]
If we have the time I think it would be worth showing some cells with hyperlinks in the static calendar. I think this would be a common use case for a calendar, i.e. an events calendar linking out to event pages.

**Comment by ianmcburnie** [comment]
The Date Textbox only seems to be showing an example for single date selection scenario. I don't see an example for date ranges that would require two textboxes (as seen on CoreUI).

Screen Shot 2023-03-28 at 7 26 17 PM

**Pull request merged**
