### PR TITLE
Fix for combobox icon stretching

### PR DESCRIPTION
**Pull request by seangates**
## Description
- fix for icon in the combobox stretching

## Screenshots

**Before**

image

**After**

image

### CODE REVIEW

**Comment by ianmcburnie** [comment]
@seangates Thanks for this. Not a huge deal, but Is there anyway to get rid of the three additional `background-size` cascades? Or is that something that can only be resolved as part of a mixin refactor in https://github.com/eBay/skin/issues/276?

**Comment by seangates** [comment]
Let's do that as a refactor. I did notice the duplicated rule, but this is just a bug fix.

**Comment by ianmcburnie** [comment]
No problem. I'm surprised the linter didn't complain, actually. Or maybe that rule is still disabled.

**Comment by seangates** [comment]
Yeah. 🤷‍♂️

**Pull request merged**
