### PR TITLE
Menu: DS4 migration to eBayUI;

### LINKED ISSUE #275: Menu: retrofit/normalize DS4 and DS6
Shouldn't be too many differences in terms of the menu markup, but we might as well continue with our pattern of creating `base`, `ds4` and `ds6` src folders.

Although this one might get interesting due to the shared "dropdown" styles with combobox (issue #223). Not sure what order you want to tackle this in, or maybe altogether, suffice to say... good luck!

### PR DESCRIPTION
**Pull request by seangates**
## Description
- normalized CSS to use the existing `dropdown.css`
- docs are normalized to existing examples
- updated tests removing deprecations

## Context
The retrofit follows the other retrofit work in the other components.

## References
Fixes #275 

## Screenshots
image

image

### CODE REVIEW

**Comment by ianmcburnie** [comment]
I see a few visual changes to the DS4, not sure if this is intentional not. If it is, they should be documented in the PR.

For example, currently in ds4 menu with keyboard focus on 2nd item:

screen shot 2018-08-02 at 2 47 12 pm

With this PR:

screen shot 2018-08-02 at 2 47 04 pm

I see that your thought is probably to normalize the menu to look like the combobox, but I would say it should be the other way around, because we had actual specs for the ds4 menu, but never did for combobox.

The grey background looks pretty neat, but I'm not sure where it has come from...? Come to think of it, it's a colour contrast issue anyhow.

Another example, currently in DS4, fake menu links are black:

screen shot 2018-08-02 at 2 49 16 pm

In this PR they are grey:

screen shot 2018-08-02 at 2 49 28 pm

One bug I found in Safari:

screen shot 2018-08-02 at 2 53 02 pm

**Comment by seangates** [comment]
@ianmcburnie Let me look this over. Should be easy fixes

**Comment by senthilp** [comment]
Good catch. We should try our best to make sure the DS4 UI looks exactly the same before and after. This is the only reason, teams have agreed for the migration.

**Comment by seangates** [comment]
@senthilp Yup. Working on it as we speak. There was some dupe CSS. Lots of moving parts in these PRs! 👍

**Comment by seangates** [comment]
@ianmcburnie @sendlo @senthilp Issues should be addressed. Please review again and let me know if you see anything amiss.

**Comment by seangates** [comment]
@sendlo @ianmcburnie @senthilp I found that the button arrow color was wrong. I've fixed it for all expand buttons using "regular"

**Comment by sendlo** [comment]
Fake menu has the checkmark misaligned.
New:
screen shot 2018-08-06 at 11 30 01 am

Old:
screen shot 2018-08-06 at 11 32 31 am

**Comment by seangates** [comment]
@sendlo Fixed. Ready for review again.

**Pull request merged**
