### PR TITLE
fix(badge): changed styles to align correctly

### PR DESCRIPTION
**Pull request by agliga**
## Description
Changed some styles in badge (added flex, removed box-border, changed padding to be equal)
On the large one the text is very close to the sides, but this can only be fixed by adding an unequal padding, causing the badge to not be a circle. If that's fine I can change it.

## Screenshots
Screen Shot 2021-09-30 at 8 23 23 AM

### CODE REVIEW

**Comment by ianmcburnie** [comment]
Seems like we lost the wider padding when it's two digits?

Previously:

Screen Shot 2021-09-28 at 1 33 17 PM
 
Figma:
Screen Shot 2021-09-30 at 10 19 43 AM

**Comment by ianmcburnie** [comment]
Don't we need to add a child element, so that there is a flex child?

**Comment by agliga** [comment]
Screen Shot 2021-09-30 at 9 19 29 PM

Got it working by reworking `min-width`

**Comment by agliga** [comment]
> Don't we need to add a child element, so that there is a flex child item?

Not necessarily. The text itself I believe is treated as the child element.

**Comment by agliga** [comment]
Screen Shot 2021-10-01 at 12 48 10 PM
>

**Review by ianmcburnie — APPROVED** [review]

**Pull request merged**
