### PR TITLE
Icon Button added icon-btn__svg class to apply styles in cases where svg is not direct descendant

### LINKED ISSUE #1480: Button: hover/focus does not work with aria-label and icon variant
`ebay-button` when it has variant="icon" and aria-label - renders an wrapper span over the svg which is causing the hover/focus state to not work. 

https://github.com/eBay/skin/blob/master/src/less/icon-button/base/icon-button.less#L38-L39
https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-button/index.marko#L74

Maybe the code should be less specific
```
&:focus svg,
&:hover svg {
  .customFillProperty(icon-button-icon-hover-foreground-color);
}
```

### PR DESCRIPTION
**Pull request by austingardner**
## Description
Didn't notice any visual changes to icon button.. we will have to verify in ebay-ui-core that nothing breaks here. 

## References
closes #1480.

### CODE REVIEW

**Review by agliga — COMMENTED** [review]
The specific styles are intentional, when we have an icon button with a dropdown caret, it applies the styles to the caret as well which is the issue.

What I think we need is to have a class that we select for the icon or somehow ignore the styles for the caret portion. 
(see menu-button with icon only example)

**Comment by ianmcburnie** [comment]
Two options:

1. Add a `.icon-btn__icon` class to the SVG (this will help differentiate it from the svg icons that are in the dropdown overlay)
2. Add a grouped selector `.icon-btn > span > svg`

Option 1 is probably the best.

**Comment by austingardner** [comment]
Hey @ianmcburnie and @agliga - do these changes match what you were thinking? Let me know if I need to make any more changes here.

**Comment by ianmcburnie** [comment]
Yes. If we go with this, we also need to add this new class to the examples and storybook (and the CoreUI component).

**Comment by agliga** [comment]
> Hey @ianmcburnie and @agliga - do these changes match what you were thinking? Let me know if I need to make any more changes here.

Kinda

I would remove the direct selector and have it do
.icon-btn svg.icon-btn__icon

**Comment by ianmcburnie** [comment]
Andrew, we probably need to leave in the old selector for backwards compatibility. We can remove it in v13.

**Comment by agliga** [comment]
> Andrew, we probably need to leave in the old selector for backwards compatibility. We can remove it in v13.

Yes probably unless the old syntax just never worked.

**Comment by ianmcburnie** [comment]
Austin, can you go with `__icon` instead of `__svg`, and then add it to the example code and stories and we should then be good to merge.

**Comment by ianmcburnie** [comment]
@agliga I also have to ask... why is CoreUI adding the <span> wrapper around <svg>?

**Comment by agliga** [comment]
> @agliga I also have to ask... why is CoreUI adding the `<span>` wrapper around `<svg>`?

Hmm, this is what its doing:
```
    $ var hasAriaLabel = Boolean(htmlAttributes["aria-label"]);
    <${!hasAriaLabel ? null : "span"} aria-hidden="true">
        <${input.renderBody}/>
    </>
 ```

**Comment by ianmcburnie** [comment]
Hmm, I don't think this is correct. An icon button shouldn't have a span wrapper. It should always have aria-hidden=true on the svg tag.

```html
<button class="icon-btn" type="button" aria-label="Menu">
    <svg class="icon icon--menu" focusable="false" width="16" height="16" aria-hidden="true">
        <use xlink:href="icons.svg#icon-menu"></use>
    </svg>
</button>
```

**Comment by austingardner** [comment]
Closing per our discussion offline - aria-label should be placed on the button.

**Pull request closed without merging**
