### PR TITLE
feat: combobox with actionable icon

### PR DESCRIPTION
**Pull request by raveenakothapally**
Fixes #1025 

PLEASE SQUASH.

### CODE REVIEW

**Comment by raveenakothapally** [comment]
> @raveenakothapally Curious as to why you aren't doing the same thing as recent textbox changes.
> 
> For example, here is combobox with non-actionable icon (as it is in 10.0.0 branch):
> 
> ```
> <span class="combobox__control">
>     <input placeholder="Combobox" role="combobox" type="text" aria-haspopup="listbox" aria-owns="listbox1" />
>     <svg class="icon icon--dropdown" focusable="false" height="8" width="8" aria-hidden="true">
>         <use xlink:href="#icon-dropdown"></use>
>     </svg>
> </span>
> ```
> 
> Would changing to this, not work?:
> 
> ```
> <span class="combobox__control">
>     <input placeholder="Combobox" role="combobox" type="text" aria-haspopup="listbox" aria-owns="listbox1" />
>     <button class="icon-btn" type="button" aria-label="Expand Suggestions">
>         <svg class="icon icon--dropdown" focusable="false" width="8" height="8" aria-hidden="true">
>             <use xlink:href="#icon-dropdown"></use>
>         </svg>
>     </button>
> </span>
> ```

I updated the textbox to also consume from this PR as they both now consume actionable classes instead of hosting their own changes.
As far as the combo-box actionable icon goes, I thought we are adding another icon (Preferably at the start of the combo-box input. For example to toggle dropdown or anything like that. Check the attached image.

Screen Shot 2020-02-10 at 4 25 47 PM

**Comment by ianmcburnie** [comment]
@raveenakothapally Sorry for the confusion, but we only want the option of having the dropdown icon be actionable. This should make things much simpler, and match what you originally had for textbox.

**Comment by raveenakothapally** [comment]
> @raveenakothapally Unfortunately, by deleting the styles from textbox, this would be a breaking change. Is it not possible to update combobox in the same way that you originally did for textbox, without adding a new modifier class to actionable?

I am trying to have a shared class for making actionable icons on any module. Fo ex, in future if another module needs actionable icon, i can just use this and avoid copying styles. Just curious, what are the repercussions of having such breaking change on the textbox that you are eluding to?

**Comment by ianmcburnie** [comment]
@raveenakothapally Sure! :-) If anybody is using an actionable icon in their textbox in v5.0.0, and they upgrade to 5.1.0, their UI would be broken because the styles no longer exist. They would have to go and update their code, so that technically makes it a breaking change.

I can see the value in what you are doing, but I think for now in v5 branch we'll need to keep combobox consistent with textbox if we can.

**Comment by raveenakothapally** [comment]
> @raveenakothapally Sure! :-) If anybody is using an actionable icon in their textbox in v5.0.0, and they upgrade to 5.1.0, their UI would be broken because the styles no longer exist. They would have to go and update their code (to use the new modifier), so that technically makes it a breaking change.
> 
> I can see the value in what you are doing, but I think for now in v5 branch we'll need to keep combobox consistent with textbox if we can.

That makes sense. My mind is stuck in React component model where styles and class names reside within the component so that client's would not be impacted for such a change :)

**Comment by ianmcburnie** [comment]
Also, I'm going to add a bit of example JavaScript for the button functionality before it goes live.

**Pull request merged**
