### PR TITLE
Multiple icon fixes

### PR DESCRIPTION
**Pull request by agliga**
## Description
* Added `icon-attention-filled` `icon-confirmation-filled` and `icon-information-filled` to DS4 in order to provide backwards compatibility
* Fixed notice to use the new `-filled` icons
* Removed all the old shorthand icons `icon-attr`, `icon-info`, and `icon-conf`
* Fixed loading of small icons through browser.json.
* Updated `icon-camera-small` and `icon-save-small` based on design

## Context
* We kept the `-filled` icons since the syntax is better than the `-clear` version
* Icon small borwser.jsons will only load small icons on DS6 becasue DS4 does not have small icons file (Should we create in future)?

## References
Initial PR: #790 

## Screenshots
image
image

DS4 screenshot of new filled icons
image

### CODE REVIEW

**Comment by msendlakowski** [comment]
@agliga Those aren't the right screenshots, right?  It says filled but those are the default empty ones.  Is the test file off?

**Comment by agliga** [comment]
> @agliga Those aren't the right screenshots, right? It says filled but those are the default empty ones. Is the test file off?

Those are DS4 screenshots of the filled ones

**Comment by seangates** [comment]
Hmmm. Those SVG paths seem ... huge.

This PRs new heart icon (small):
```
<svg xmlns="http://www.w3.org/2000/svg" id="icon-save-small" viewBox="0 0 16 14"><path fill="#111820" fill-rule="evenodd" d="M15.74219,1.25780996 C14.9197021,0.449988173 13.8120354,-0.00121986394 12.65919,0.00194995626 C11.5298434,0.00210131843 10.4485501,0.458927913 9.66119,1.26854996 C9.42030185,1.52378011 9.19926215,1.79703838 9,2.08593997 C8.80075704,1.79704049 8.57973745,1.52378228 8.33887,1.26854996 C7.55150991,0.458927913 6.47021658,0.00210131843 5.34086998,0.00194995626 C3.60110437,-0.0181656909 2.02137712,1.01420543 1.34134583,2.61568801 C0.661314541,4.21717058 1.01558451,6.07076738 2.23827996,7.30859 L8.27344,13.6875 C8.46245236,13.886999 8.72518095,14.0000014 9,14.0000014 C9.27481905,14.0000014 9.53754764,13.886999 9.72656,13.6875 L15.74219,7.32812 C16.5475229,6.52333781 17.0000006,5.43148834 17.0000006,4.29296498 C17.0000006,3.15444162 16.5475229,2.06259215 15.74219,1.25780996 Z M14.30859,5.93358999 L9,11.54492 L3.67187997,5.91405999 C3.0140164,5.25701885 2.8184816,4.26754319 3.17697317,3.40965547 C3.53546474,2.55176776 4.37688371,1.99561126 5.30663998,2.00194089 L5.32519998,2.00194089 C5.91861334,1.99989701 6.48771057,2.23760866 6.90331999,2.66117997 C7.37317615,3.215762 7.77966267,3.82105599 8.11522999,4.46581998 C8.30518176,4.77186049 8.63980219,4.95800514 9,4.95800514 C9.36019781,4.95800514 9.69481824,4.77186049 9.88477001,4.46581998 C10.2203341,3.82103858 10.6268207,3.21572767 11.09668,2.66112997 C11.5122978,2.23757703 12.081394,1.99988385 12.6748,2.00194089 C13.2928682,1.99760533 13.8874473,2.23853049 14.32812,2.67192997 C14.7616663,3.10515399 15.0036304,3.69397799 15.0000018,4.3068662 C14.9962909,4.91975442 14.747293,5.50563871 14.30859,5.93363999 L14.30859,5.93358999 Z" transform="translate(-1.000000, 0.000000)"/></svg>
```
... and after I put it in the [SVGOMG online](https://jakearchibald.github.io/svgomg/):
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 14"><path fill="#111820" fill-rule="evenodd" d="M14.742 1.258A4.383 4.383 0 0 0 11.66.002c-1.13 0-2.21.457-2.998 1.267-.24.255-.462.528-.661.817-.2-.289-.42-.562-.661-.817A4.183 4.183 0 0 0 4.34.002a4.291 4.291 0 0 0-3.103 7.307l6.035 6.378a1 1 0 0 0 1.454 0l6.015-6.359a4.29 4.29 0 0 0 0-6.07zM13.31 5.934L8 11.544l-5.328-5.63a2.291 2.291 0 0 1 1.635-3.912h.018a2.2 2.2 0 0 1 1.578.66c.47.554.877 1.16 1.212 1.804a1.041 1.041 0 0 0 1.77 0 9.768 9.768 0 0 1 1.212-1.805 2.2 2.2 0 0 1 1.578-.66 2.334 2.334 0 0 1 1.653.67 2.292 2.292 0 0 1-.02 3.263z"/></svg>
```

**Comment by seangates** [comment]
Which makes me curious about the compression that our script is actually performing.

**Pull request merged**
