### PR TITLE
Checkbox and radio: unselected color cleanup;

### LINKED ISSUE #737: Checkbox: unchecked checkbox shows with blue border instead of grey in DS4
Skin version: 7.4.7
The DS4 unchecked checkbox shows with blue border instead of grey.
In our app:
Screen Shot 2019-08-03 at 12 17 52 AM
In Skin doc:
Screen Shot 2019-08-04 at 2 59 14 PM

### PR DESCRIPTION
**Pull request by seangates**
## Description
- fix radio and checkbox colors for foreground icons (LESS)
- fix radio and checkbox SVG in `ds6/icons.svg`
- fix radio and checkbox background Base64 variables for background icons

## Context
In looking at both checkbox and radio, I found discrepancies in both. The colors did not match other form controls, and also had some fill overrides in the foreground icons which would prevent someone from setting custom colors (if needed).

## References
Fixes #737 

#### DS4 Before

**Checkbox: DS4**
image

**Radio: DS4**
image

#### DS4 After

**Checkbox: DS4**
image

**Radio: DS4**
image

#### DS6 Before

**Radio: DS6**
image

#### DS6 After

**Radio: DS6**
image

### CODE REVIEW

**Comment by ianmcburnie** [comment]
Why not wait until we get to radios and checkboxes in the ds6.5 roadmap? Seems an awkward time to do this one. Especially now that 7.x branch doesn't have all of the refactoring that the 8.x branch has. Merge to 8.0.0 branch could be unpleasant.

**Comment by seangates** [comment]
This is product fixes that people are filing against their existing products. They are bugs that make the apps their deploying (today) look ... bad.

**Comment by seangates** [comment]
The merge isn't too bad: https://github.com/eBay/skin/pull/742

**Comment by msendlakowski** [comment]
Yeah, I agree.  We should merge them now for the 7.x release.  There are multiple requests to have them fixed.  And I don't know how quickly some of these teams will migrate to a major version update with 8.x.

**Comment by ianmcburnie** [comment]
I am completely aware that these are product bugs that look bad. We have several such others that have been so for a LONG time. The whole point of DS6.5, and the roadmap we created, is to go through these discrepancies in order. I'm pleased the merge wasn't too bad, just be careful not to get sidetracked otherwise the careful planning some of us have done is for nought.

**Pull request merged**
