### PR TITLE
Remove magic number in outline color

### PR DESCRIPTION
**Pull request by darkwebdev**
## Description

Replace color numbers with a variable

## Context

Because magic numbers are hard to maintain

Not sure if I've put the variables in the correct places...

### CODE REVIEW

**Comment by ianmcburnie** [comment]
Thanks @darkwebdev Changing target branch from master to 9.5.0...

**Comment by darkwebdev** [comment]
@ianmcburnie 👍

**Comment by ianmcburnie** [comment]
@darkwebdev You also need to run `yarn build`, and commit the generated `dist` files.

**Comment by darkwebdev** [comment]
created a proper PR #928

**Pull request closed without merging**
