### PR TITLE
Added inverted checkbox & radio icons

### LINKED ISSUE #236: Checkbox and radio not visible in white-on-black high contrast mode
See #233 for details.

screenshot 10

screenshot 14

### PR DESCRIPTION
**Pull request by ianmcburnie**
Fixes #236.

I took the existing svg paths for checkbox and radio and added `fill="#fff"` before applying base64 encoding.

I also extracted out the base64 strings as LESS variables and updated the mixins to use these new variables. In a future PR we may also want to refactor the way the icon mixins work for WHCM, but this should be a decent start for now.

screenshot 21

screenshot 22

### CODE REVIEW

**Comment by seangates** [comment]
So, you haven't done this for the inline SVG yet? Should we add that to this PR to be consistent with these icons across the board?

**Comment by ianmcburnie** [comment]
I don't believe we need to do anything for the inline SVG.

**Comment by ianmcburnie** [comment]
So I've also update icon.less with and example of how we would need to update the standalone classes too. This is certainly going to cause a lot of bloat in icon.css and skin.css once we do ALL the icons.

**Comment by ianmcburnie** [comment]
Sean correctly pointed out that icon.css is shared with inline svg icons and background svg icons. Bloating the icon.css for all these new variants of the background icons would be a big hit for those only consuming the background icons. It seems a better path forward would be to split the icon module into two, so they are not tied at the waste, so to speak. As this would be a breaking change let's save it for v6. I have removed the updates to icon.css, but let's proceed with making fixes in the places where we use background icons internally, and let's do this in a new branch and PR.

**Pull request merged**
