### PR TITLE
Icon: normalized DS4 and DS6 styles to base file

### LINKED ISSUE #705: Icon: normalize DS4 and DS6 styles to base file
Prep work for #276 

Similar to how we've normalized other modules and moved common ds4 and ds6 styles to a base folder, let's do the same for icon.

## Current

ds4/icon.less
```less
&.icon--notification {
  .background-image-base64(@ds4-icon-notification-base64);
  .icon-size-mixin('icon-notification');
}
```

ds6/icon.less
```less
&.icon--notification {
  .background-image-base64(@ds6-icon-notification-base64);
  .icon-size-mixin('icon-notification');
}
```

## Proposed

base/icon.less
```less
&.icon--notification {
  .background-image-base64(@icon-notification-base64);
  .icon-size-mixin('icon-notification');
}
```

### PR DESCRIPTION
**Pull request by ianmcburnie**
Closes #705 

Prep work for #276 

* Moves common DS4 and DS6 icons to a base file.
* Should be much clearer to see which icons are common, ds4 and ds6 now
* Fixed up a few DS4 tests.
* Removed a deprecated mixin (`background-icon-base`).
* Restored missing "filter" background icons for DS4 (not sure when they went missing)

### CODE REVIEW

**Comment by ianmcburnie** [comment]
@seangates You're right, `icon-save` doesn't seem to exist for ds4. Not sure if it ever did. I'll remove it from the test page.

**Comment by ianmcburnie** [comment]
@seangates Aha - I think `save` was re-aliased to `download`. Will update references accordingly.

**Comment by seangates** [comment]
Was it? "save" in DS6 is the heart icon.

**Comment by ianmcburnie** [comment]
Yup. You can see the alias is still there. Don't believe we ever had a heart icon for ds4.

**Pull request merged**
