### PR TITLE
feat: split icons into multiple modules

### LINKED ISSUE #1609: Icon: break up giant file into smaller, optional submodules
We might want to start looking into breaking up the large `icon.svg` file by type, e.g. star series, shipping, navigation, etc. The file is getting pretty huge now (~123kb).

We could do this in a backwards compatible way where @ebay/skin/icon brings in a file with all icons, but also have submodules for specific files, e.g.@ebay/skin/icon/stars, @ebay/skin/icon/shipping.

We'd need a simple package script that would stitch all the individual files together into the large file.

### PR DESCRIPTION
**Pull request by agliga**
Fixes #1609

- [X] This PR contains CSS changes
- [ ] This PR does not contain CSS changes

## Description
* Finalized splitting up of icons in their own modules. Modules are largely based on figma
* I have an `aliased` icon pack and a `internal` icon pack (where the internal uses icons that we use for other components, like eek and spinner)
* All icon packs now go into dist/icons. So `dist/icons/general.less` and `dist/icons/large.less`. Build system changed to do so.
* Added an icon import script which can import icons into their given pack. 
* I kept small icons and regular sized icons in the same group. 
* A follow up PR will address the global imports. 

## Screenshots
Screen Shot 2022-05-25 at 3 30 05 PM
Screen Shot 2022-05-25 at 3 30 10 PM

## Checklist
- [X] I verify the build is in a non-broken state
- [X] I verify all changes are within scope of the linked issue

- [X] I regenerated all CSS files under dist folder
- [X] I tested the UI in all supported browsers
- [X] I tested the UI in dark mode and RTL mode
- [ ] I added/updated/removed Storybook coverage as appropriate

### CODE REVIEW

**Comment by agliga** [comment]
* Fixed an issue with dropdown icon not rendering correctly.

**Comment by agliga** [comment]
Also updated icon creation guide to detail new steps. 
https://github.com/eBay/skin/issues/1423

**Review by ianmcburnie — COMMENTED** [review]
I think we can remove the `docs/static/common` folder. Maybe got included by accident, as I also see the icons one level above. Actually, we might want to shuffle them all under `docs/static/icons`?

**Comment by ianmcburnie** [comment]
I think organisationally thinks could be improved. For example, why isn't "delete" under content. Why isn't "cart" under interface. Should the four content icons just be merged into interface? etc etc I think a sweep through with design team would be good.

**Comment by ianmcburnie** [comment]
I think we now might need to elaborate with more instructions in the SVG section, on how to include different SVG files. We currently just provide a link to the SVG source folder.

**Review by ianmcburnie — APPROVED** [review]
LGTM! Made a few comments that can be addressed before release.

**Pull request merged**
