### PR TITLE
add lasso flags to less.browser.json

### PR DESCRIPTION
**Pull request by PrashantAshok**
## Description
Minor optimization - Load the appropriate less files as per the lasso flags.

### CODE REVIEW

**Comment by ianmcburnie** [comment]
Thanks @PrashantAshok. You said you tested this and everything works fine for you?

**Comment by PrashantAshok** [comment]
Yep.

**Comment by ianmcburnie** [comment]
Hmm, actually. I seem to remember keeping it like this for a reason. What if teams want access to DS4 variables **and** DS6 variables in the same page? This is also a breaking change for any teams that do currently. So I guess I'll change the target to 7.0.0 while we mull it over.

**Comment by PrashantAshok** [comment]
Sure. imho, That doesn't feel right - trying to access DS4 variables in DS6. The app UI should be consistent.

**Comment by ianmcburnie** [comment]
Yeah, it doesn't feel totally right, but I wanted to leave it there while teams transition over. And perhaps they were using some utility variables/mixins that were not carried over into ds6.

I agree with you though, and I think at some point we will make the full switch. Version 7.0.0 feels good to me.

**Comment by ianmcburnie** [comment]
@seangates ok, with this?

**Comment by seangates** [comment]
@ianmcburnie Yeah! Sorry, forgot to add my approval.

One thing that comes out of this: we could theoretically drop the DS prefix for variables names, and even normalize some of our color systems a bit.

**Comment by ianmcburnie** [comment]
Yep, we can drop the prefixes when we manage to get DS4 and DS6 onto the same naming convention.

**Pull request merged**
