### PR TITLE
Fixed Outline Offset, Long Text Scrolls Correctly

### LINKED ISSUE #1303: Breadcrumbs: Entire text is not showing up and not scrollable, if the text is long
# Bug Report

## eBayUI Version: 
    "@ebay/ebayui-core": "^6.0.0-4",
    "@ebay/skin": "^11.0.0-4",

## Description
The breadcrumb is not showing the complete text, if the text is long.
Only the last portion of the breadcrumb is visible.
CC: @agliga @ianmcburnie 

## Screenshots
image

### PR DESCRIPTION
**Pull request by austingardner**
## Description
This PR fixes the outline offset on the breadcrumbs, and allows the breadcrumbs to scroll when there is long text. I hid the scroll bar, which seemed optimal because adding more height to the line to make room for the scrollbar didn't look quite right. 

I also added JS to scroll to the end in the demo page when text overflows. 

## References
Closes #1303, #1459 

### Scrolled to end
Screen Shot 2021-06-08 at 4 40 36 PM

### Outine
Screen Shot 2021-06-08 at 4 40 59 PM

### CODE REVIEW

**Comment by ianmcburnie** [comment]
Seeing an issue where page is getting horizontal scrollbars:

Screen Shot 2021-06-08 at 5 47 42 PM

**Review by ianmcburnie — APPROVED** [review]
Looks good! Just make sure to check in all browsers.

**Review by agliga — APPROVED** [review]

**Comment by agliga** [comment]
Do we want this for `12.6.0` or for `13.0.0`?

**Comment by ianmcburnie** [comment]
No breaking changes, so let's go for 2.6.0.

**Pull request merged**
