### PR TITLE
Upgraded devDeps

### PR DESCRIPTION
**Pull request by ianmcburnie**
Upgraded following outdated devDeps (it's good if we can keep on top of this):

Screen Shot 2019-08-16 at 11 46 59 AM

After doing so, babel started complaining about missing `core-js-pure`, so I added it. It's used by `listbox.js` for `findIndex`. It brings in a lot of additional js so I may refactor this in future.

### CODE REVIEW

**Comment by msendlakowski** [comment]
@ianmcburnie Hemnath is almost done testing the 9.0.0 release.  Are we OK potentially delaying the release in order to regress this?  Or should we wait for the next major?

**Comment by ianmcburnie** [comment]
These are just devDeps.  Mainly stuff for the website. This PR doesn't affect our CSS, so we should be good here, unless I'm missing something?

**Comment by msendlakowski** [comment]
Right.  I was thinking about ebayui core.  I ran update there yesterday and saw some actual dependency changes, so I wanted to take a beat and test more thoroughly.  I'll be doing that today though.

**Comment by ianmcburnie** [comment]
Yep, dependencies should be upgraded as soon as a new milestone branch is created. We have to keep on top of that for security reasons.

**Pull request merged**
