### PR TITLE
Editable combobox

### LINKED ISSUE #399: Combobox: enhance for editable (non-readonly) scenario
Going forward, the main use case for combobox will be for the editable scenario (ebayui layer will add autocomplete/filtering logic). Let's add tests, examples and documentation and update CSS where necessary in support of that.

### PR DESCRIPTION
**Pull request by ianmcburnie**
## Description

Minimal LESS/CSS changes. Mostly docs updates.

1. Updated combobox examples with editable versions
1. Left one example of readonly combobox, with explanation of it's issues
1. Normalized the combobox css by back porting the scrollable/max-height functionality of ds6 to ds4
1. Normalized the combobox docs so that both ds4 and ds6 now both have a scrolling example (I will do the same for menu in a follow up PR).
1. Stripped out most of the combobox JS functionality on DS6 page (part of my plan to simplify and unify the two sites)
1. Updated test pages

## Context

For a custom select, we want people to use the listbox module rather than a readonly combobox.

## References

Closes #399 

## Screenshots

screen shot 2018-10-10 at 2 55 07 pm
screen shot 2018-10-10 at 2 55 13 pm
screen shot 2018-10-10 at 2 55 17 pm
screen shot 2018-10-10 at 2 55 27 pm
screen shot 2018-10-10 at 2 55 32 pm
screen shot 2018-10-10 at 2 55 37 pm

### CODE REVIEW

**Comment by seangates** [comment]
Seeing this, can you reproduce, @ianmcburnie?:

image

**Comment by ianmcburnie** [comment]
@seangates I believe that's an existing issue: https://github.com/eBay/ebayui-core/issues/434

**Comment by seangates** [comment]
I actually think it's fixed in #391, but it will go into v7.

**Comment by seangates** [comment]
@ianmcburnie So, why are we keeping the readonly combobox? Isn't that what the Listbox is a replacement for?

**Comment by ianmcburnie** [comment]
Well, that fix would be nice to have in 6.1.0. That's why it's sometimes important not to fix multiple issues in a single PR (as tempting as it may be!) - so we can separate them out for different types of releases (patch/minor/major). Hopefully you can just cherry pick that commit or something. If you think it can wait till 7.0.0 that's fine too (although coreui might not pick up that release version for a while yet).

Readonly combobox works well on desktop, so I don't want to give up on it just yet, and also it would be a breaking change if we were to completely remove it.

**Comment by ianmcburnie** [comment]
@seangates Apart from those concerns, does this look okay? This will unblock me to move on with further normalization for menu, and stripping down more js.

**Comment by seangates** [comment]
I will remove the code to fix the arrow from #391, and create a new PR for just it. Then we can put it into 6.1.0.

**Pull request merged**
