### PR TITLE
Dialog retrofit

### LINKED ISSUE #221: Dialog: retrofit DS6 markup changes to DS4
I think the main changes are:

* mask element was removed in favour of transitioning the alpha channel of root element
* heading element does not exist in ds6

### PR DESCRIPTION
**Pull request by seangates**
## Description
- normalized dialog CSS
- updated docs
- removed "search" dialog type

>**Note:** the animations for the DS4 docs do not currently work. I de-prioritized that work in favor of making sure I covered all the styling use cases. It may not even be worth it to do, since it will work in the eBayUI component, regardless.

## Context
As part of the DS4 retrofit.

One issue we should discuss: other buttons added to the dialog outside of the body. Skin for DS4 will allow a second button to be added as a "back" button, with an additional button label for the close button of the dialog (which is currently just the `X` close icon).

I'd like some opinions on this and will make my thoughts known throughout the discussion.

## References
Fixes #221 

## Screenshots

**Before**

image

image

image

**After**

image

image

image

### CODE REVIEW

**Comment by msendlakowski** [comment]
It looks good to me.  Regarding the close icon.  It looks like the user (and ebayUI component) could just remove the close icon from the markup.

@yomed   Since DS4 supports a version of the dialog with a "back" rather than close icon, we need to support that somehow.  I think we just need to allow applications to hide the "close" button.  They can take care of adding the back behavior themselves.  But in the documentation we'll have to warn them that by removing the close button they may not pass accessibility.

**Comment by msendlakowski** [comment]
@seangates  Can you specify in the documentation that the first h2 tag we find will automatically be used for the dialog title in DS4.  Could we update the DS4 demo to have 2 headers so its clear that the first is the title?

**Comment by seangates** [comment]
@msendlakowski Yes! I completely forgot that part. I will add it.

**Comment by seangates** [comment]
@msendlakowski Updated with info in the docs.

**Comment by seangates** [comment]
Okay, after some discussion, I will add a class that allows hiding of the dialog's close button, but only for DS4. This class will not be present in DS6.

**Comment by seangates** [comment]
Okay, I've added the `dialog--hide-close-button` class and some instructions about it. Please let me know your thoughts.

**Comment by msendlakowski** [comment]
@seangates Did you decide not to give it a "ds4" name?  We'll just have to make sure DS6 users understand this isn't supported in DS6 until the design team gives us the go-ahead.

**Pull request merged**
