### PR TITLE
229 - Combobox iOS mWeb cursor fix

### PR DESCRIPTION
**Pull request by dasarianudeep**
## Description
CSS change to not to display cursor for ios mobile

## References
https://github.com/eBay/ebayui-core/issues/229

## Screenshots
img_0589

### CODE REVIEW

**Comment by seangates** [comment]
@dasarianudeep Can you also show the behavior when the issue is fixed?

**Comment by dasarianudeep** [comment]
No cursor post change:
img_0591

**Comment by seangates** [comment]
@dasarianudeep I rebased the branch with your changes.

**Comment by seangates** [comment]
@dasarianudeep Why did the dist files change so much? Did your editor modify their whitespace?

The only changes we should see are the ones to add the new selector and rule.

**Comment by dasarianudeep** [comment]
@seangates I had fixed my editor issue. It looks fine now.

**Comment by seangates** [comment]
Awesome! Thanks. I will merge even though you don't have GPG signing set up yet. Can you please do that for future commits?

**Comment by ianmcburnie** [comment]
Thanks for the fix.

@sgates @dasarianudeep I pulled the latest 6.0.0 branch and now when I run a build I see an unsynced dist file:

screen shot 2018-07-29 at 1 45 43 pm

**Comment by seangates** [comment]
@ianmcburnie I just noticed this today, when I got started on today's work. We need this file. I will commit it and create a PR for safety.

**Comment by seangates** [comment]
@ianmcburnie I believe it's part of `combobox.css` and not part of `dropdown.css`. We _should_ remove it. This is an artifact.

**Pull request merged**
