### PR TITLE
feat: updated to use marko-run instead of jekyll

### LINKED ISSUE #2069: Website: replace Jekyll with Marko Run
Is this goodbye Ruby? More details to follow.

https://github.com/marko-js/run

### PR DESCRIPTION
**Pull request by agliga**
Fixes #2069

- [ ] This PR contains CSS changes
- [X] This PR does not contain CSS changes

## Description
* Changed site to use marko run. 

## Things to check
* I updated this branch manually from master. There were some changes which did not conflict, so I had changed them manually
* Make sure all the components come up properly and things look fine. 
* Remember, we can iterate! Lets check the main things work and the structure is fine. 

## Notes
* All source files are not in `src/routes`, `src/modules` and `src/components`. Modules is a custom directory which will render each file in that directory in the navbar and on the page. Components are common components, like highlight etc
* There needs to be a bit of cleanup for each of the routes layouts. I think we can combine these, but that is going to be in a followup.
* All events are triggered from `main.js`. 
* No more building docs/other files. These are directly being referenced in the code and will cause a rerender when theres a change
* Cleaned up a lot of the commands. Now to start the server do `npm run dev`. Build only builds files and needs to be run each time. `npm run deploy` builds the server for deployment. I left start as it, but we might want to change that. 

## Checklist
- [X] I verify the build is in a non-broken state
- [X] I verify all changes are within scope of the linked issue

### CODE REVIEW

**Comment by ArtBlue** [comment]
It's looking good so far. One thing I noticed...

image

Is there a way to have the example markup inside the syntax highlighting instead of being an attribute? This isn't ideal as it looks/feels broken and losing the syntax highlighting is probably going to cause issues for longer examples.

**Comment by ArtBlue** [comment]
It looks like live reload isn't working on the docs.

**Comment by agliga** [comment]
> It looks like live reload isn't working on the docs.

Is this with `npm run dev`? I believe it was working

**Comment by agliga** [comment]
> It's looking good so far. One thing I noticed...
> 
> image
> Is there a way to have the example markup inside the syntax highlighting instead of being an attribute? This isn't ideal as it looks/feels broken and losing the syntax highlighting is probably going to cause issues for longer examples.

Yah, this was an issue that I had tried to get to work, but marko team said we are unable to access render body on the server. I had it the way you proposed initially but I was not able to get it to work. I believe there might be a way to use tranformers to access it, but have to check with them. 
We can do client side rendering and then extract the rendered body and syntax highlight it (I had this approach too), but it was way too intensive and slow to load.

**Comment by ArtBlue** [comment]
> > It looks like live reload isn't working on the docs.
> 
> Is this with `npm run dev`? I believe it was working

Yes, I'm doing `npm run dev`. It seems to be working for style updates, but not for markup.

**Comment by agliga** [comment]
> > It looks like live reload isn't working on the docs.
> 
> Is this with `npm run dev`? I believe it was working

Okay, I see. Its due to the modules directory. I think this might be due to how we are importing them using the glob pattern. 
Might need to see if there's a way to get those to be targeted for live reload. 
Regardless hitting reload on the page will show the changes if you change things in the modules.

**Comment by ArtBlue** [comment]
> > It's looking good so far. One thing I noticed...
> > image
> > Is there a way to have the example markup inside the syntax highlighting instead of being an attribute? This isn't ideal as it looks/feels broken and losing the syntax highlighting is probably going to cause issues for longer examples.
> 
> Yah, this was an issue that I had tried to get to work, but marko team said we are unable to access render body on the server. I had it the way you proposed initially but I was not able to get it to work. I believe there might be a way to use tranformers to access it, but have to check with them. We can do client side rendering and then extract the rendered body and syntax highlight it (I had this approach too), but it was way too intensive and slow to load.

Gotcha. Maybe we can look into it a bit more in the future.

**Comment by ArtBlue** [comment]
> > > It looks like live reload isn't working on the docs.
> > 
> > 
> > Is this with `npm run dev`? I believe it was working
> 
> Okay, I see. Its due to the modules directory. I think this might be due to how we are importing them using the glob pattern. Might need to see if there's a way to get those to be targeted for live reload. Regardless hitting reload on the page will show the changes if you change things in the modules.

Do we have to use the glob pattern? It would be great to retain live reload.

**Review by ArtBlue — APPROVED** [review]
We can iterate on this to get live reload working. This is a huge first step. Looks good.

**Comment by agliga** [comment]
> We can iterate on this to get live reload working. This is a huge first step. Looks good.

Will do, we figured out the cause but still need to figure out the solution (we have a solution, but need to run it by the marko team)
I will go ahead and merge this to unblock other PRs and iterate on the live reload

I also updated the code to have highlight be inline.

**Pull request merged**
