### PR TITLE
Minor tooltip fixes

### PR DESCRIPTION
**Pull request by seangates**
## Description
- fixes the alignment of the pointer
- adds missing pointers for DS6 (left top, left bottom, right top, right bottom)
- fixes z-index issue with pointer (z-index for the overlay)
- fixes close button alignment

## Context
Minor issues were uncovered when implementing the Tooltip component.

## References
https://github.com/eBay/skin/pull/467#issuecomment-442650174

### CODE REVIEW

**Comment by DylanPiercey** [comment]
I think things look good. Is it alright that in the screenshot below the arrow is a bit off?

image

**Comment by seangates** [comment]
Oh, let me fix the docs.

**Comment by seangates** [comment]
@DylanPiercey The docs have the top/bottom and left/right properties set manually. For the component we calculate these in JS. I've fixed the docs to now have the correct property values. Thanks for spotting this!

**Comment by seangates** [comment]
@DylanPiercey @ianmcburnie I just made one more small update, relating to the pointer's background color and drop shadow (for the new right-top/right-bottom and left-top/left-bottom) locations. Please let me know if you have any questions.

**Pull request merged**
