### PR TITLE
Removing class:current

### PR DESCRIPTION
**Pull request by RajaRamu**
## Description
Removing class:current and applying style with span[aria-current]

### CODE REVIEW

**Comment by ianmcburnie** [comment]
Sorry, but 15 commits including a couple of merges makes me nervous. I'm sure Git would figure it all out, but for good PR etiquette we should only be seeing 1 commit here. Please use a new branch or squash/rebase as necessary.

**Comment by seangates** [comment]
I definitely prefer rebase, since these are all the exact same commits, already in the 3.5.0 branch.

**Comment by RajaRamu** [comment]
i rebased, it still shows same commits. not sure why. let me try few things if that would help

**Comment by seangates** [comment]
👍

**Comment by ianmcburnie** [comment]
I hope all these commits aren't in 3.5.0...! Unsquashed I mean.

**Pull request closed without merging**
