### PR TITLE
fix(icon-button): proper colors for certain filled icons - informatio…

### LINKED ISSUE #1596: icon-button: unable to render a non-black icon color
see core ui issue [1557](https://github.com/eBay/ebayui-core/issues/1557)

### PR DESCRIPTION
**Pull request by austingardner**
## Description
This PR fixes the issue with confirmation, attention, and information icons. I added a new selector that fills the svg with the proper color. 

The one question I had was how to handle the visited styles for the icon link - let me know if I need to change those up. 

## References
closes #1596 

## Screenshots
Screen Shot 2021-11-18 at 10 27 48 AM

Screen Shot 2021-11-18 at 10 27 57 AM

### CODE REVIEW

**Review by agliga — APPROVED** [review]

**Comment by ianmcburnie** [comment]
I don't think the color filled icons are supposed to have the grey background/matte. Will check in with @rbascue

**Comment by ianmcburnie** [comment]
Thanks for the clarification @rbascue. They will be removed.

**Comment by ianmcburnie** [comment]
Updated. Requires a quick re-review from @agliga 

Screen Shot 2021-12-01 at 12 03 35 PM

**Review by agliga — APPROVED** [review]
Yes, it looks good

**Pull request merged**
