### PR TITLE
feat: updated magenta 4 color and rebuilt

### LINKED ISSUE #1909: Token: color-magenta-4 is incorrect
The token value for the core token `--color-magenta-4` is incorrect. It is currently the same value as `--color-magenta-6`, which is `#82187C`. It's actual value is `#D11DA4`.

### Incorrect value
Screen Shot 2022-10-21 at 9 19 38 AM

### Correct values
Screen Shot 2022-10-21 at 9 21 28 AM

### PR DESCRIPTION
**Pull request by martin-ebay**
Fixes #1909

- [x] This PR contains CSS changes
- [ ] This PR does not contain CSS changes

## Description
updating magenta 4

## Checklist

- [x] I verify the build is in a non-broken state
- [ ] I verify all changes are within scope of the linked issue

- [x] I regenerated all CSS files under dist folder
- [ ] I tested the UI in all supported browsers
- [ ] I did a visual regression check of the components impacted by doing a Percy build and approved the build
- [ ] I tested the UI in dark mode and RTL mode
- [ ] I added/updated/removed Storybook coverage as appropriate

### CODE REVIEW

**Comment by agliga** [comment]
There's some deleted files in dist. Just verify running the build doesn't add them again. 
I'm fine merging like that if those are gone in src.

**Comment by martin-ebay** [comment]
@agliga there are large and small versions of the svgs that got deleted. I did a fresh build after nuking the dist folder locally.

**Comment by ArtBlue** [comment]
@martin-ebay , change the target branch to the skin repo `15.2.0`.

**Review by ArtBlue — APPROVED** [review]

**Comment by martin-ebay** [comment]
@ArtBlue updated the base branch. Looks like I don't have access to merge

**Review by agliga — APPROVED** [review]

**Pull request merged**
