### PR TITLE
Add support for arc

### PR DESCRIPTION
**Pull request by DylanPiercey**
## Description
Adds support for [arc](https://github.com/eBay/arc) & webpack.

## Context
The top level entry points are now <strike>JavaScript</strike> LESS files which work in both webpack and lasso. In lasso the `browser.json` is still used to remap to the appropriate file for the design system, however arc flags can also be used.

## References
Implements #567

### CODE REVIEW

**Comment by ianmcburnie** [comment]
Looks backwards compatible to me (?) - so I guess I can target this for 7.2.0 instead of 8.0.0.

**Comment by DylanPiercey** [comment]
@ianmcburnie it should be backward compatible. I am currently validating all of these changes in some apps. It will take a bit of time to do this.

**Comment by ianmcburnie** [comment]
Ok. No hurry on my side. So take as long as you need.

**Comment by DylanPiercey** [comment]
After testing this out with the webpack sample I found that having the top level js files cannot be ergonomically imported into the app. Instead using top level `less` files allows using your own `less` file to import these (in webpack apparently you cannot import js from a `less` file :\).

My current approach leaves the `browser.json`'s mostly the same and they should still be able to be imported as they are into existing lasso apps. For a webpack app (or also in a lasso app if they prefer) you can explicitly import the less file, eg: `@import "~@ebay/skin/button.less"` and this can now be adapted by arc.

The only downside is that in webpack land the consumer now needs to use the `less-loader` where as they don't in the lasso world. I think this is okay, what do you think @ianmcburnie?

**Comment by seangates** [comment]
Requiring the use fo `less-loader` seems fine to me.

I do want to re-confirm having DS4 be the default, as I believe we discussed already, that when we flip the arc/lasso flag from DS6 to DS4 we'd be doing this as part of a major version (e.g. breaking change), correct?

**Comment by ianmcburnie** [comment]
Yep, I think this is okay.

We shall be keeping DS4 the default for the time being.

**Comment by seangates** [comment]
@ianmcburnie Even through the next major version?

**Comment by ianmcburnie** [comment]
It depends when that next major version comes. There are currently no plans to release a major version for any other type of breaking changes.

**Comment by seangates** [comment]
Well, this would be a breaking change, so I'm just clarifying that a flag change would only happen down the road.

**Comment by ianmcburnie** [comment]
Yep, I think Dylan and I are both aware that changing default from ds4 to ds6 would be a breaking change, and so this can go into 7.2.0.

**Pull request merged**
