### PR TITLE
233-whcm - Fixes for background icons within components when in Windows High Contrast Mode

### LINKED ISSUE #233: Icon: Critical background icons disappear in windows high contrast mode (WHCM)
By default, Windows hides background images in high contrast mode (EDIT: windows no longer hides background images in Edge. See latest comments below for details). CSS allows us to override this using `-ms-high-contrast-adjust: none;` or to provide custom high-contrast mode icons via the `-ms-high-contrast` media query.

Not all background-icons need the override, only critical ones or those that give affordance.

screenshot 9

screenshot 10
screenshot 12
screenshot 13
screenshot 14

screenshot 11

screenshot 18

### PR DESCRIPTION
**Pull request by seangates**
## Description
These updates add a "light" version of the SVG icons for use in background SVGs when in Windows High Contrast Mode.

>**Note:** This collection of fixes is for 5.1.0, with additional changes planned for 6.0.0 which will <strike> move all components to inline SVG. The future changes will then</strike> not penalize developers who choose to use inline SVG only.

## Context
When a user enters Windows High Contrast Mode they currently end up losing the background SVGs because IE/Edge remove them. We need to provide a way for users to be able to still see the icons for our controls.

## References
Fixes #233 

## Screenshots
**Breadcrumb**
image

**Button - dropdown version**
image

**Button - dropdown version - icon only**
image

**Checkbox**
image

**Combobox, Menu, and Fake Menu**
image

**Dialog**
image

**Notice**
image

**Pagination**
image

**Radio**
image

**Select**
image

### CODE REVIEW

**Comment by ianmcburnie** [comment]
There's a lot of unrelated/prior commits in here, which makes me a bit nervous.

Also, is that breadcrumb icon `#fff`? Looks grey to me.

**Comment by ianmcburnie** [comment]
Oh, it's probably because you are targeting master. Please target 5.1.0.

**Comment by seangates** [comment]
@ianmcburnie Fixed the base branch to 5.1.0. Whoops.

**Comment by seangates** [comment]
Adding the high contrast (white) version for the breadcrumb.

**Comment by ianmcburnie** [comment]
Sorry, looks like my other PR has now caused you conflicts in this branch. As soon as those are resolved I will pull and test locally. Cheers.

**Comment by seangates** [comment]
@ianmcburnie Ready for review again.

**Comment by PrashantAshok** [comment]
Hey @seangates - looks like you missed adding in `dist/less/ds6/mixins.less` & `dist/less/ds6/variables.less`

**Comment by seangates** [comment]
@PrashantAshok I believe they're there:

Mixins: https://github.com/eBay/skin/pull/242/files#diff-93b9adb73845c66b44d3805a6f68e702
Variables: https://github.com/eBay/skin/pull/242/files#diff-395189fe4009fab795b347a118c48d9f

**Comment by seangates** [comment]
Ah, they need to be newly built. Let me open a new PR for just those two files. 👍

**Pull request merged**
