### PR TITLE
Rounded Carousel Items -> Website

### PR DESCRIPTION
**Pull request by austingardner**
## Description
Rounded the corners of the carousel list items on the website. 

In an attempt to match what I saw on playbook, I added more border-radius on the smaller carousel items, and a much more subtle border-radius on the big items.

Squash, please!

Note 1: add these changes in `docs/src/less/base/index.less`, so they will apply to ds4 as well, which might not be ideal.. should I add them in the `docs/src/less/ds6/index.less` file instead?

## Screenshots
DS6
Screen Shot 2021-01-08 at 2 48 41 PM
Screen Shot 2021-01-08 at 2 48 27 PM
Screen Shot 2021-01-08 at 2 48 18 PM

DS4
Screen Shot 2021-01-08 at 2 49 15 PM
Screen Shot 2021-01-08 at 2 49 07 PM
Screen Shot 2021-01-08 at 2 48 56 PM

### CODE REVIEW

**Review by ianmcburnie — CHANGES_REQUESTED** [review]
I see the RTL changes in here too. Can you keep those changes separate from this PR please?

**Comment by austingardner** [comment]
Okay I took out the commits from the other branch. I was thinking that the other one would just merge first and then we wouldn't have any merge conflicts but I shouldn't have worried about that.

**Comment by ianmcburnie** [comment]
So let's use a border radius of 10px for ds6, and 3px for ds4/legacy.

Also, no need to use custom properties for website. Less variables are fine.

**Comment by austingardner** [comment]
updated screenshots based on new `border-radius` changes.

**Review by agliga — APPROVED** [review]

**Review by ianmcburnie — APPROVED** [review]

**Pull request merged**
