### PR TITLE
Notice: added DS6 flyout notice (and new Bubble)

### PR DESCRIPTION
**Pull request by ianmcburnie**
## Issue Number

#451 

## Goal(s)

1. Add DS6 flyout notice
1. Provide path forward for normalized DS4/DS6 flyout notice & tooltip
1. Added DS6 tooltip too (#111)

## Changes

1. Added new DS4 & DS6 bubble module (this is a purely presentational module, for the "speech bubble" base styes)
1. Added new DS6 flyout notice
1. Refactored DS4 flyout notice to use new bubble (breaking change)
1. Refactored DS4 tooltip to use new bubble (breaking change)
1. Refactored file structure of notice module
1. Updated all existing tests
1. Updated all existing docs

## Context

When starting to work on the flyout notice & tooltip normalization, I noticed that they both share a lot of duplicate code with regards to the "bubble". I also noticed that the bubble in the DS6 tooltip markup had deviated from DS4, adding an extra element or two. I decided to extract this bubble piece into it's own module and normalize it. This bubble is now used by flyout notice and tooltip, and should prove useful as a standalone module (albeit a slightly abstract one).

The new bubble also simplifies how the "pointer" works. Previously the top pointers used some hacky/magic CSS, which I found a little difficult to reason with when coming back to it. Now all pointers use a square that gets rotated and masked. It adds an extra element to the DOM, in order to mask it properly, but is easier to follow. In future we can replace this mask with `clip-path`, when it has better browser support.

In terms of the DS6 flyout notice, I have taken some liberties here. Basically this design pattern is deprecated, and we no longer encourage it's use, but we should still provide it in order for pages to get more quickly from DS4 to DS6 via Skin (but we wont add a flyout notice component to eBayUI - that would probably be a waste of time). We can tweak it a little before release if necessary.

I also took some liberties with DS4 tooltip (as this never really existed in DS4). I have simply given each type of tooltip a blue top border (which matches up with an "Information Notice").

I have not changed any of the styles related to page notice and inline notice. They just got moved around a lot as a result of the refactoring. I basically separated out notice.less into 3 individual files, one for page, inline and flyout. This for me makes things a little easier to follow, as we weren't getting much benefit out of the grouped selectors in one giant file anyhow.

All of this work should now make it trivial to add a DS6 Tooltip for #111.

## Tested

Safari, Firefox, Chrome, IE, EDGE.

## Known Issues

1. <strike>The drop shadow light source needs more work. In DS4 the light source should be from top left. In DS6. It should be directly from above.</strike>
1. <strike>The top border and top arrows are not appearing in IE & EDGE.</strike> 
1. DS6 added 4 new pointer locations. I have not added these yet.

### Previous issue with bubble pointer

See below how the pointer was actually sitting on top of the bubble. Although this only become apparent when setting the pointer to a different colour than the bubble, I wanted to make sure this would not happen going forward, so I added a mask element.

screen shot 2018-11-08 at 11 19 51 am

screen shot 2018-11-08 at 11 08 01 am

screen shot 2018-11-04 at 1 10 09 pm

screen shot 2018-11-04 at 1 10 24 pm

### New Bubble Module:

DS4

screen shot 2018-11-13 at 3 56 07 pm

DS6

screen shot 2018-11-13 at 3 49 00 pm

### Example of how tooltip uses new bubble module:

screen shot 2018-11-08 at 1 16 46 pm

### Example of how flyout notice uses new bubble module:

screen shot 2018-11-08 at 1 21 38 pm

### New DS6 Flyout Notice (using bubble):

screen shot 2018-11-13 at 3 49 19 pm

### CODE REVIEW

**Comment by ianmcburnie** [comment]
A thought occurred to me that I could just have bubble available as a set of mixins, rather than classes. So flyout notice and tooltip would *mix in* the bubble styles. Class `bubble__mask` becomes `tooltip__mask` and  class `bubble__cell` becomes `tooltip__cell` etc. This approach would help with specificity and prevent misuse of bubble.

**Comment by seangates** [comment]
That makes a bunch of sense to me, too.

**Comment by ianmcburnie** [comment]
Ok. Hold off on reviewing further while I tinker around with that. Thanks!

**Comment by ianmcburnie** [comment]
Drop shadows updated. Conversion to mixins not done yet.

**Comment by ianmcburnie** [comment]
With the new base styles for bubble in place, it was trivial for me to add the DS6 tooltip. Might help making sense of the PR and my intended direction! I still need to convert the bubble base styles to mixins though.

**Comment by ianmcburnie** [comment]
@seangates I think the mixin approach is looking okay, but so that you can compare, I pushed those changes to a different branch: https://github.com/eBay/skin/tree/bubble-as-mixin. If we want to go down that path I will merge those changes into here. We can chat offline if necessary.

**Comment by seangates** [comment]
@ianmcburnie No worries. I'm getting the skeleton done for the component in parallel, so when you're markup is done I can integrate it. There are some things that won't change before you're done. 😉 

I'll take a look.

**Comment by ianmcburnie** [comment]
Closing this one. Will send out the new mixin-based one soon.

**Pull request closed without merging**
