### PR TITLE
Patch dialog ds4 padding

### PR DESCRIPTION
**Pull request by seangates**
## Description
- change padding calculation to use 14px;

## Context
Helps better align body content with the dialog header.

## References
n/a

### Before

image

### After

image

### CODE REVIEW

**Comment by seangates** [comment]
Thanks, @ianmcburnie!

**Comment by ianmcburnie** [comment]
Gah! And right after I merge I realize the generated CSS was missing.

**Comment by seangates** [comment]
100% my fault. Sorry, Ian.

**Comment by ianmcburnie** [comment]
No worries. I'll just direct commit it now.

**Pull request merged**
