### PR TITLE
chore: remove deprecations for v14 #1650

### PR DESCRIPTION
**Pull request by ianmcburnie**
Issue #1650

- [X] This PR contains CSS changes

## Description

Remove all deprecated parts of API.

* Old non normalized DS4 semantic tokens and primitives
* <strike>Window Notice module</strike>
* Color module (seems limited value with new, minimal token system) - can maybe revisit if teams ask for it
* Old, abbreviated color names (e.g. `color-y1` is now `color-yellow-1`
* Section-title__cta (was superseded by "Linked Section Title" in v13.2.0)

## Notes

I left in `btn--wide`. Not sure if safe to remove yet. Will revisit it later.

## Checklist

- [X] I verify the build is in a non-broken state
- [X] I verify all changes are within scope of the linked issue

- [X] I regenerated all CSS files under dist folder
- [X] I tested the UI in all supported browsers
- [X] I tested the UI in dark mode and RTL mode
- [X] I added/updated/removed Storybook coverage as appropriate

### CODE REVIEW

**Comment by ArtBlue** [comment]
I'm seeing some inconsistencies in storybook on local vs. prod; could be some local issue...

**Local**
image

**Prod**
image

**Comment by ArtBlue** [comment]
Also some inconsistencies on skin site local vs. prod...

**Local**
image

**Prod**
image

**Review by ArtBlue — COMMENTED** [review]
The code looks ok but I noticed some visual issues on skin site and storybook.

**Comment by ianmcburnie** [comment]
@ArtBlue Yeah, after this I'm going to do a full sweep through everything, storybook included, and see what I broke :-)

**Review by ArtBlue — APPROVED** [review]

**Review by agliga — APPROVED** [review]

**Comment by ianmcburnie** [comment]
Going to restore Window Notice. CoreUI will add deprecation notice and we can remove it completely next time around.

**Pull request merged**
