### PR TITLE
Fix for small screens; Fix headers padding;

### PR DESCRIPTION
**Pull request by seangates**
## Description
- fixes the width issue on small screens
- resets the headers with some padding for better page anchor nav (it was set before, maybe a bad rebase?)

## Context
Fixed because:
- Things didn't look good on mobile
- Things didn't navigate well, and the left nav header was mashed up against the top of the viewport

### Before
image

### After
image

### CODE REVIEW

**Comment by seangates** [comment]
@ianmcburnie Just want to be sure you're aware this is merging to master. I think it's fine given it's simply an update to the docs, and not to Skin itself, which means we don't need to version anything just for the docs.

**Comment by ianmcburnie** [comment]
Yep, master branch is correct in this case.

**Comment by seangates** [comment]
@ianmcburnie Please review once more, as I have a fix for Firefox in there now.

**Comment by ianmcburnie** [comment]
Looks good in Firefox now. Thanks.

**Pull request merged**
