### PR TITLE
Changing font-family to ds6 standard

### PR DESCRIPTION
**Pull request by RajaRamu**
For context, an email thread:

>Hi Team,
>
>As of now, ebay-font carries default typography as font-family: "Market Sans","Helvetica Neue", Helvetica,Arial,Roboto,sans-serif
> 
>Do we need to upgrade ds6 as font-family: "Market Sans",Arial,sans-serif
>
>Thanks
>Raja

With a reply from Joe:

> The DS6 version is correct.

### CODE REVIEW

**Comment by seangates** [comment]
Was just about to say the same, @ianmcburnie.

Please run `yarn build` after you've made your changes to any source files.

**Comment by ianmcburnie** [comment]
@RajaRamu What's the urgency of this? Can it go out two weeks from now in 3.5.0? Or is a patch release this Friday preffered?

**Comment by seangates** [comment]
@ianmcburnie As far as I'm concerned this is a patch, as it only changes the fallback font families, not the primary font-family.

**Comment by ianmcburnie** [comment]
Good point Sean!! I didn't think of that.

**Pull request closed without merging**
