### PR TITLE
Adding small modifier for select;

### PR DESCRIPTION
**Pull request by seangates**
## Description
Adds a `small` modifier to allow a smaller version of the select.

## Context
When placed inline, the normal size is too large with default page text.

### CODE REVIEW

**Comment by ianmcburnie** [comment]
Should the height also be updated for the standard (non-borderless version)?

screen shot 2018-05-14 at 3 44 50 pm

screen shot 2018-05-14 at 5 48 09 pm

Have you tried it side-by-side with the small button?

**Comment by seangates** [comment]
Why was this closed?

**Comment by ianmcburnie** [comment]
Accidentally close this. Sorry! But please see may questions regarding height and side-by-side alignment.

**Comment by seangates** [comment]
Will revisit this when we want to add small modifier for all form elements.

**Pull request closed without merging**
