### PR TITLE
Updated stepper to DS v3.1.1

### PR DESCRIPTION
**Pull request by agliga**
PLEASE SQUASH

## Description
Updated stepper to use new DS 3.1.1 designs.

## Context
* Renamed stepper to be progress-stepper. Kept old stepper class as is. Added new look and feel to new stepper class
* ~~This module will need a lot of cleanup in the next major version. A lot of the old classes are not being used. That said, I left them in for backwards compatibility. This has been simplified since there really is only two transition states: blue (which is used for all active states) and grey (for not yet activated).~~
* I copied the confirmation, information, and attention filled icons to have `stepper` icons. The main reason for this was that confirmation needed a blue color and it had fill set already. For consistency, I coped the other two also
* ~~I left in a lot of things for backwards compatibility. It still works fine, but some colors might be off (will have blue lines instead of green). Teams will probably need to update just the icons for now. Ebayui should have no breaking changes, (but will require an ebayui change, and we should probably include this change in `7.1.0` or else it will look off).~~
* ~~Removed badge depedency. I called the class `step` instead, which should be the current step. I can rename it to `stepper__step` or `stepper__badge`.~~ Removed badge depdency. Added `role=img` as attribute checker for "badge"
* Made sure RTL cases work
* Removed a lot of the modifiers. Basically only `aria-current` causes the colors to change. Default would be "active" state (ie current or complete). All others after `aria-current` are upcoming. For cases where we want all items to be "active", remove `aria-current` or put it at the end. For all cases upcoming I added a modifier (both per item and separator or the preferred way which is global in items) for `--upcoming`. I kept both because other teams might want to use it per items rather than the whole thing. But if we see it's not used, we can remove it. 
* ~~Forced item width of `80px` This kinda fixes the slight off center look. This also made each item take the same amount of space.~~ Forced item width of `32px`. This makes the lines overlap correctly
* Updated docs

## References
#1287 

## Screenshots
Screen Shot 2021-01-25 at 12 38 20 PM
Screen Shot 2021-01-25 at 12 38 26 PM

Screen Shot 2021-01-21 at 2 36 24 PM
Screen Shot 2021-01-21 at 2 36 31 PM
Screen Shot 2021-01-21 at 2 36 08 PM

### CODE REVIEW

**Comment by ianmcburnie** [comment]
Any way to fully right-justify the last horizontal item? The first item seems fully left-justified, but the last item has some noticeable spacing after the icon.

**Comment by ianmcburnie** [comment]
Also, yes - to satisfy BEM - please rename `.step` to `.stepper__number` or maybe even just use `.stepper__icon > span[role=img]` if we don't need another class hook (that should be backwards compatible too).

**Comment by ianmcburnie** [comment]
Given the backwards compatibility issues, I am proposing we rename this new version as `progress-stepper`. We can leave the old version around (hidden from docs) and then remove it in v13.

**Review by ianmcburnie — CHANGES_REQUESTED** [review]
Given the backwards compatibility issues, I am proposing we rename this new version as progress-stepper (all classnames will need updating too). We can leave the old version around (hidden from docs) and then remove it in v13.

**Comment by agliga** [comment]
> Given the backwards compatibility issues, I am proposing we rename this new version as progress-stepper (all classnames will need updating too). We can leave the old version around (hidden from docs) and then remove it in v13.
> 
> This actually works out nicely as I wanted to rename spinner to progress-spinner, and name bar as progress-bar. So they will all be clearly named by their purpose.

@ianmcburnie PR should be updated now

**Comment by ianmcburnie** [comment]
Looks great. Code much simplified with this new design. 

I think these file might have been left in by mistake though:

dist/stepper copy/ds4/stepper.css
dist/stepper copy/ds6/stepper.css
dist/progress-stepper/ds4/stepper.css
dist/progress-stepper/ds6/stepper.css

**Comment by agliga** [comment]
> Looks great. Code much simplified with this new design.
> 
> I think these files might have been left in by mistake though:
> 
> dist/stepper copy/ds4/stepper.css
> dist/stepper copy/ds6/stepper.css
> dist/progress-stepper/ds4/stepper.css
> dist/progress-stepper/ds6/stepper.css

Yes, I had the server running when I copied those files.
On that note, I think we should change the build to remove dist on each build and then rebuild it. I noticed that there are some other variable files like notice which are still in dist but do not exist in src anymore.

**Comment by ianmcburnie** [comment]
Good idea, Andrew!

**Review by ianmcburnie — APPROVED** [review]

**Pull request merged**
