### PR TITLE
Icon creation readme

### PR DESCRIPTION
**Pull request by seangates**
## Description
Created documentation around adding SVG icons to Skin.

## Context
We want developers to know how to go through the process of adding an icon. It has relatively few steps, but there are some nuances to creating an icon. I tried my best to keep it as simple as possible, which is why I added screen shots and code examples.

image

### CODE REVIEW

**Comment by senthilp** [comment]
Thanks for doing this @seangates. Appreciate it.

**Comment by seangates** [comment]
@PrashantAshok I will do that during merge.

**Comment by ianmcburnie** [comment]
Just a thought, but instead of storing the screenshots in version control, you could potentially just drag and drop them into any GitHub preview editor to receive a permanent URL. Or perhaps use our internal CDN Upload portal. Totally fine if you want to leave them as is.

**Comment by seangates** [comment]
@ianmcburnie Done. Please review once more.

**Pull request merged**
