### PR TITLE
Drawer (bottom-container)

### PR DESCRIPTION
**Pull request by agliga**
## Description
This PR contains two parts
1) Split up dialog to use common components (added them in dialog-mixins and in vairables)
2) Added bottom container component

## Context
* Added new styles and reused a lot of dialog
* Added tests/docs/storybook
* Added some javascript to simulate it. We can also add scroll events to show that it expands. 
* Added proper animations for it. 
* For handle, made it a button and added `aria-label` to make is accessible. Otherwise it is just styled with CSS

## References
#822

## Screenshots
image
image
image

Animations
bottom-container

### CODE REVIEW

**Comment by ianmcburnie** [comment]
@agliga Seeing a miss alignment with the handle, something possibly crept in to your commit...?

Screen Shot 2020-04-03 at 12 53 04 PM

**Comment by agliga** [comment]
> @agliga Seeing a miss alignment with the handle, something possibly crept in to your commit...?
> 
> Screen Shot 2020-04-03 at 12 53 04 PM

It was working in firefox but not chrome and such. I pushed a fix to get it to work

**Comment by ianmcburnie** [comment]
As discussed offline, let's rename to "Drawer".

**Comment by agliga** [comment]
> As discussed offline, let's rename to "Drawer".

Done

**Pull request merged**
