### PR TITLE
Btn cell issue

### PR DESCRIPTION
**Pull request by seangates**
## Description
- `btn__cell` was breaking by having 100% height, so removed
- forced to update module containers to accommodate
- fixed the expander menu accordingly, since `display: inline-flex` resets element's layout

## Context
The marketplace (internal to eBay) was broken because the menu's height was outside of the `iframe`, and therefore being calculated over and over because it was always resizing outside of the iframe container.

### Before
image

### After
image

### CODE REVIEW

**Comment by ianmcburnie** [comment]
I'm still seeing some alignment issues on the test page across safari, chrome and IE. 

screen shot 2019-02-01 at 3 08 28 pm

screen shot 2019-02-01 at 3 08 37 pm

screen shot 2019-02-01 at 3 10 35 pm

**Comment by seangates** [comment]
@ianmcburnie Yeah, these are now existing issues. Can we create a new issue for those in order to unblock the immediate issue at hand (marketplace breaking)?

**Comment by seangates** [comment]
(e.g. I solved the major issues: cell height, dropdown location)

**Comment by ianmcburnie** [comment]
I wouldn't say there's any huge rush to fix the marketplace, given that it's a beta version. Unless it's really horribly, horribly broken. I think we might as well get button fixed fully before doing another prerelease. Otherwise we just end up doing another round of testing anyway.

**Comment by seangates** [comment]
Well, this PR is targeted specifically to fix the Marketplace. Are you suggesting I close this then extend the fixes to also include #546 (alignment issue)?

**Comment by ianmcburnie** [comment]
I'm a little nervous of the knock on effects of these changes to button. Particularly the change to height 100% on the button cell. The changes fix the marketplace, but not sure if they have made the alignment test page better, worse or same. I think it would be best to do one PR that addresses the underlying alignment issue *and* the marketplace issue. Just to avoid any back and forth.

**Comment by seangates** [comment]
Sure. I'll take a clean look at all of it.

**Pull request closed without merging**
