### PR TITLE
feat(eek): updated to use SVGs for arrow

### PR DESCRIPTION
**Pull request by agliga**
## Description
Updated EEKs to use svg for arrow instead of normal CSS. Aligned it better

## Screenshots
Screen Shot 2021-04-05 at 2 18 55 PM

### CODE REVIEW

**Review by ianmcburnie — CHANGES_REQUESTED** [review]
Looks like the code example sections need updating.

**Comment by agliga** [comment]
> Looks like the code example sections need updating.

Done, always forget about that hah

**Comment by ianmcburnie** [comment]
Instead of:

"EEK Rating B. Range is from A++ to E"

Can we avoid the grammar and go with something that is more key/value pair like:

"EEK Rating: B. Low Range: A++. High Range: E".

I don't know if "low" & "high" is right, or "start" and "end", maybe you can check the EEK vocabulary.

**Comment by ianmcburnie** [comment]
I think we should go with `role=figure`:

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Figure_Role

<blockquote>The ARIA figure role can be used to identify a figure inside page content where appropriate semantics do not already exist. A figure is generally considered to be one or more images, code snippets, or other content that puts across information in a different way to a regular flow of text.</blockquote>

Seems more appropriate?

**Comment by ianmcburnie** [comment]
I'm kind of undecided on this. The arrow alignment is better, but even by my eye I can see the rough edges where the two SVGs meet:

Screen Shot 2021-04-06 at 11 47 06 AM

**Review by ianmcburnie — APPROVED** [review]

**Pull request merged**
