### PR TITLE
Fix close icon sizing

### PR DESCRIPTION
**Pull request by DylanPiercey**
## Description
Fixes the size for the close icon.

## References
Fixes https://github.com/eBay/skin/issues/642

### CODE REVIEW

**Comment by seangates** [comment]
@DylanPiercey Given that there are conflicts in this branch, please merge 7.3.0 back to your branch, then re-run the build.

**Comment by DylanPiercey** [comment]
Rebased 🙂

**Comment by DylanPiercey** [comment]
I mean it _should_ be safe since it's just an icon resize. Don't feel great about rushing through a release for it though unless someone is really needing it quickly.

**Comment by seangates** [comment]
Feels safe to me.

**Comment by ianmcburnie** [comment]
Let's hold off and put it in a 7.3.1 patch with this one:

https://github.com/eBay/skin/issues/645

**Pull request merged**
