### PR TITLE
Fix for dialog button breaking layout #306

### PR DESCRIPTION
**Pull request by prabhurangan**
## Description
Fixed the dialog button which breaks to next line, by setting the custom style to accessibility <DIV> element 

## Context
We have the makeup-keyboard-trap which creates a <DIV> element on dialog pop up, which makes the button to break to next line.  added custom style to the <DIV> element to fix this issue.

screen shot 2018-08-23 at 5 52 42 pm

## References
#306 

## Screenshots
Before: 
screen shot 2018-08-23 at 5 52 42 pm

After:
screen shot 2018-08-23 at 5 52 54 pm

### CODE REVIEW

**Comment by DylanPiercey** [comment]
I just realized that I think this is just because we are currently putting these divs outside the dialog. It might be simpler to just make this consistent with ebay ui and make the keyboard trap on the `dialog__window` [here](
https://github.com/eBay/skin/blob/master/docs/src/js/ds6/main.js#L149)

**Comment by prabhurangan** [comment]
no more needed. will send new PR

**Comment by seangates** [comment]
@DylanPiercey Gotcha. So the keyboard trap is not currently set on the dialogs in the Skin docs?

**Comment by DylanPiercey** [comment]
@seangates it was set, just on the wrong element which caused the inserted divs to be outside of the dialog and caused the div to basically act as a br.

**Pull request closed without merging**
