### PR TITLE
SVG: removed duplicate icon-clear element

### PR DESCRIPTION
**Pull request by stevedoty**
## Description
I deleted old code that was left when icon-clear was updated

## Context
I deleted it because it was just clutter

## References

https://github.com/eBay/skin/issues/1102

### CODE REVIEW

**Comment by stevedoty** [comment]
let me know if it looks good

**Comment by ianmcburnie** [comment]
@stevedoty Just checking, did you delete from src then run the generator tool? This is the best way to ensure src and dist are in sync.

https://github.com/eBay/skin/blob/master/scripts/generate-images.js

**Comment by stevedoty** [comment]
I used yarn build to produce distribution files

**Comment by agliga** [comment]
> I only edited the src file. I used yarn build to produce distribution files.

You should run the generator tool after changing the svgs. 
`scripts/generate-images.js` 
It might not change anything however. Just let us know. 
Otherwise the change looks good to be.

**Comment by ianmcburnie** [comment]
I'll merge this at the same time we merge over 10.4.0 to master

**Pull request merged**
