### PR TITLE
Spinner: created new version for DS6

### LINKED ISSUE #901: Spinner: update fill to latest blue (DS6)
New spinner SVG asset needs uploading with latest blue for ds6 (#3665F3).

https://ir.ebaystatic.com/cr/v/c1/spinner30x30.svg

https://github.com/eBay/skin/blob/master/src/less/spinner/base/spinner.less#L3

### PR DESCRIPTION
**Pull request by ianmcburnie**
Closes #901

I ran the existing SVG through SVGOMG, changed the fill color for a ds6 version, then uploaded both assets:

http://ir.ebaystatic.com/cr/v/c1/skin/svg/spinner/v1/ds4/spinner.svg
http://ir.ebaystatic.com/cr/v/c1/skin/svg/spinner/v1/ds6/spinner.svg

We may want to consider just using an actual SVG tag in future, but for now this is a simple, quick update of the current background svg.

Screen Shot 2019-11-13 at 7 23 01 PM
Screen Shot 2019-11-13 at 7 23 18 PM

### CODE REVIEW

**Comment by seangates** [comment]
Me and my nits. Nothing we can do, really, but this kind of stuff bugs me.

image

**Comment by ianmcburnie** [comment]
@seangates Can you verify if it was present in the existing SVG or not? If not, then this is probably caused by the SVGOMG optimizations. I could try running it through again with different params.

**Comment by seangates** [comment]
Let me try.

**Comment by seangates** [comment]
Existing spinner: https://ir.ebaystatic.com/cr/v/c1/spinner30x30.svg

image

**Comment by ianmcburnie** [comment]
Thanks @seangates I recommend not zooming to 1000% in order to avoid triggering OCD. Ha ha. In all seriousness, thanks for spotting this. Great eye for detail!

**Comment by seangates** [comment]
🤷‍♂ Hey, we all have our demons!

**Comment by seangates** [comment]
But also, it likely does cause just a slight mismatch in render calculations, and can make things seem blurry, or "off" to folks.

**Comment by ianmcburnie** [comment]
Yeah, it's been like this forever though, right? I'd like to push through this PR so that at least DS6 has the right color. We can make a new ticket to try and get a new asset from design.

**Comment by seangates** [comment]
Yes, let's create a story to correct the original asset.

**Pull request merged**
