### PR TITLE
Actionable: Normalize between DS4 and DS6

### PR DESCRIPTION
**Pull request by ianmcburnie**
# Issue #440 

## Goal(s)

1. Make actionable available in ds6 docs
1. Normalize actionable source files

## Main Changes

1. Created a `base/actionable.less` file
1. Added a ds6 test page (we are starting to create duplication across our ds4/ds6 test pages though, which we'll need to address at some point)
1. Moved `ds6/actionable.html` to `common/actionable.html`
1. Some CSS property changes (I had to make some adjustments due to the recent ds4/ds6 icon normalization - mainly alignment related)

### DS4

screen shot 2019-01-07 at 5 45 52 pm

Detail:

screen shot 2019-01-07 at 5 47 02 pm

### DS6

screen shot 2019-01-07 at 5 45 43 pm

Detail:

screen shot 2019-01-07 at 5 46 52 pm

### CODE REVIEW

**Comment by seangates** [comment]
Is there a reason these is a different height between a `button` and `href`?

image

**Comment by seangates** [comment]
Looks like we need to add `display: block;` to the `` to remove some extra padding on the bottom.

Thoughts?

**Comment by seangates** [comment]
Also, from the test page:

image

Demo page looks correct, though:

image

**Comment by ianmcburnie** [comment]
@seangates Looks like that height difference issue was already there. Will look into it though.

I'll see what's going on with that test page. Thanks!

**Pull request merged**
