### PR TITLE
Changed floating label to support new rounded textarea

### PR DESCRIPTION
**Pull request by agliga**
## Description
* Changed floating label to be in boxed textbox.
* Updated colors to match new designs

## Context
* Updated makeup-floating-label to support these new changes
* Added a help text to all textboxes
* Had to make error to apply to label since there is a different color. 
* Tried to remove placeholders when I could since it would interfere.

## References
#1256 

## Screenshots
Screen Shot 2020-11-05 at 12 30 28 PM
Screen Shot 2020-11-05 at 12 30 33 PM
Screen Shot 2020-11-05 at 12 30 40 PM
Screen Shot 2020-11-05 at 12 30 44 PM

### CODE REVIEW

**Review by ianmcburnie — COMMENTED** [review]
Haven't looked at everything yet, but my first thought is that the helper text element may be an unnecessary addition as we have that covered in the field module. I guess it would be good to make sure that is still working with these changes.

https://ebay.github.io/skin/#field

**Comment by agliga** [comment]
> Haven't looked at everything yet, but my first thought is that the helper text element may be an unnecessary addition as we have that covered in the field module. I guess it would be good to make sure that is still working with these changes.
> 
> 
> 
> https://ebay.github.io/skin/#field

Is field still going to be used since it seems like floating label is the preferred?
I think it makes sense the helper text to go with textfield because it should be used with floating label and field is not used in floating label. 
We shouldn't have to use field to show the help text imo.

**Review by austingardner — APPROVED** [review]
LGTM

**Comment by ianmcburnie** [comment]
@agliga Field will still be used, as there is also the option to not use a floating label.

Screen Shot 2020-11-06 at 8 43 44 AM

At this point I'm not sure if helper text is *always* under the floating label, or whether it can sometimes be above or to the side. That was why field was introduced - to remove all the different layout responsibilities for description and error text from the textbox module itself. If this new helper text is always guaranteed to be underneath a floating label textbox, then I guess it wouldn't hurt to include it within floating-label's responsibilities. Maybe speak with Randy. If there's any chance the text can go in other places then I'd prefer that to be the responsibility of a lightweight layout module like field. 

So, couple of options:

1. Keep as is, but perhaps rename the helper-text to description, more in line with the naming in field
1. Move helper-text out of floating label and incorporate the floating label + textbox into the field description examples

One other variant of the helper text is the text to the right:

Screen Shot 2020-11-06 at 8 48 13 AM
Screen Shot 2020-11-06 at 8 48 08 AM

**Comment by agliga** [comment]
> @agliga Field will still be used, as there is also the option to not use a floating label.
> 
> Screen Shot 2020-11-06 at 8 43 44 AM
> 
> At this point I'm not sure if helper text is _always_ under the floating label, or whether it can sometimes be above or to the side. That was why field was introduced - to remove all the different layout responsibilities for description and error text from the textbox module itself. If this new helper text is always guaranteed to be underneath a floating label textbox, then I guess it wouldn't hurt to include it within floating-label's responsibilities. Maybe speak with Randy. If there's any chance the text can go in other places then I'd prefer that to be the responsibility of a lightweight layout module like field.
> 
> So, couple of options:
> 
> 1. Keep as is, but perhaps rename the helper-text to description, more in line with the naming in field
> 2. Move helper-text out of floating label and incorporate the floating label + textbox into the field description examples
> 
> One other variant of the helper text is the text to the right:
> 
> Screen Shot 2020-11-06 at 8 48 13 AM
> Screen Shot 2020-11-06 at 8 48 08 AM

Sounds good. I am leaning towards 1 then. I will see how it works to get the right aligned text as well, it should be easy. 
One of the things it seems like is that helper text is going to be pretty common for textfields which is why I added it. 
I will speak to Randy and see what he says.

**Comment by agliga** [comment]
> > @agliga Field will still be used, as there is also the option to not use a floating label.
> > Screen Shot 2020-11-06 at 8 43 44 AM
> > At this point I'm not sure if helper text is _always_ under the floating label, or whether it can sometimes be above or to the side. That was why field was introduced - to remove all the different layout responsibilities for description and error text from the textbox module itself. If this new helper text is always guaranteed to be underneath a floating label textbox, then I guess it wouldn't hurt to include it within floating-label's responsibilities. Maybe speak with Randy. If there's any chance the text can go in other places then I'd prefer that to be the responsibility of a lightweight layout module like field.
> > So, couple of options:
> > 
> > 1. Keep as is, but perhaps rename the helper-text to description, more in line with the naming in field
> > 2. Move helper-text out of floating label and incorporate the floating label + textbox into the field description examples
> > 
> > One other variant of the helper text is the text to the right:
> > Screen Shot 2020-11-06 at 8 48 13 AM
> > Screen Shot 2020-11-06 at 8 48 08 AM
> 
> Sounds good. I am leaning towards 1 then. I will see how it works to get the right aligned text as well, it should be easy.
> One of the things it seems like is that helper text is going to be pretty common for textfields which is why I added it.
> I will speak to Randy and see what he says.

For now, while waiting I updated it to use `textbox__description`, we can always change it and remove it later based on what Randy says.

**Comment by ianmcburnie** [comment]
This example looks a little off:

Screen Shot 2020-11-11 at 7 08 35 PM

**Comment by agliga** [comment]
> This example looks a little off:
> 
> Screen Shot 2020-11-11 at 7 08 35 PM

How are you getting that?
It looks like that is unfocused state with placeholder (also did you get the latest makeup floating label module, that might be it)
This is what I'm getting on localhost with safari:
Screen Shot 2020-11-12 at 8 47 09 AM
Screen Shot 2020-11-12 at 8 47 17 AM

**Comment by ianmcburnie** [comment]
Oh, I thought you'd updated package.json with latest makeup-floating-label.

**Comment by agliga** [comment]
> Oh, I thought you'd updated package.json with latest makeup-floating-label.

Sorry, forgot to push up the commit, it should be good to go now 👍

**Review by ianmcburnie — COMMENTED** [review]
Looking REALLY good. Could you please add another example in the field section of "Text below floating label field", after these two:

Screen Shot 2020-11-12 at 9 45 45 AM

**Comment by agliga** [comment]
> Looking REALLY good. Could you please add another example in the field section of "Text below floating label field", after these two:
> 
> Screen Shot 2020-11-12 at 9 45 45 AM

Added floating label example
Screen Shot 2020-11-12 at 11 16 18 AM
Screen Shot 2020-11-12 at 11 16 23 AM

**Review by ianmcburnie — APPROVED** [review]

**Pull request merged**
