### PR TITLE
fix(progress-spinner): changed to use inline SVG

### PR DESCRIPTION
**Pull request by agliga**
## Description
So exported progress spinner from CDN and added it as an asset of skin. Then I used it inline in as an SVG. 
This fixes the issue with background icon being mangled and encoded improperly. 
I also added CSS variables to make dark mode work properly. 

I left in `background-image` code for backwards compatibility. I added a new class to remove background-image (I don't think it's needed but we don't need to make that request).
I also revered all the other changes with inline SVG in CSS. 

## References
https://github.com/eBay/skin/issues/1648

## Screenshots
Screen Shot 2022-01-26 at 10 31 28 AM
Screen Shot 2022-01-26 at 10 31 35 AM

### CODE REVIEW

**Review by ianmcburnie — CHANGES_REQUESTED** [review]
I think it's also worth keeping the example in the docs without the modifier (until we get to v14). Have that as the first/default example and perhaps briefly explain its potential pitfalls. This helps give a little context around why the modifier is needed. Otherwise it could come across as a poor implementation on our part.

**Comment by agliga** [comment]
> I think it's also worth keeping the example in the docs without the modifier (until we get to v14). Have that as the first/default example and perhaps briefly explain its potential pitfalls. This helps give a little context around why the modifier is needed. Otherwise it could come across as a poor implementation on our part.

I'm not sure about that. 
Ideally we want people to use the new way going forward. There should be no reason for them to use the old way. It still works but if they look at this we want them to migrate and use the SVG icon instead.
Also a question I also would ask, is how many people are using spinner without ebayui component? I doubt very many so this is still an edge case.

**Comment by ianmcburnie** [comment]
My main problem is, that as somebody who has taken a lot of care over the consistency of the docs and the BEM syntax, is that this modifier seems like a glaring mistake without any context. If I was to look at it, I'd think "This modifier seems redundant!". This may seem small, but it's the small things that add up.

Secondly, a bit like asking "how many a11y users do we have?", we should also try and avoid asking "how many non ebayui component users do we have?". A huge parts of skin's success has been due to always considering the non-js framework user first. If we get that right, the rest always falls into place. At this point I'm not entirely sure that nobody would find the simpler markup and background-image approach useful...I vote to keep it around until v14 then re-assess.

**Comment by ianmcburnie** [comment]
Just thought... can we use the `:empty` selector at all here?

**Comment by agliga** [comment]
Updated the PR to use `:empty` and I removed the new selector.

**Review by ianmcburnie — APPROVED** [review]
Let's merge for a new pre-release and come back and see if we can fix the "wobble" later.

**Pull request merged**
