### PR TITLE
Fix checkbox icon color

### PR DESCRIPTION
**Pull request by msendlakowski**
## Description
Updated the color for the checkbox icon. Also removed redundant color declarations.

## Context
The color declarations in the more complex selector appeared to be redundant. When removed the color on `.checkbox__icon svg` was used.

## References
Fixes https://github.com/eBay/skin/issues/765

## Screenshots
Screen Shot 2019-08-16 at 10 06 27 AM

Screen Shot 2019-08-16 at 9 07 19 AM

### CODE REVIEW

**Comment by seangates** [comment]
We now have a discrepancy in color from foreground and background:

image

(Both DS4 and DS6.)

**Comment by seangates** [comment]
**Edit:** Looking more closely it's DS4-only that has the issue.

**Comment by seangates** [comment]
Also, can we look at what the color was in v7 and v8? Because this feels like a yo-yo to me.

**Comment by msendlakowski** [comment]
@seangates It looks like in 8 the color was the grey color that we're fixing now.  So it was an issue in 8.  And in 7 it was blue!  

Screen Shot 2019-08-16 at 9 56 22 AM
Screen Shot 2019-08-16 at 9 56 14 AM

**Comment by msendlakowski** [comment]
I can set the color to `@color-core-gray-jet` for DS4 and it will look pretty close to the background icon color.

**Comment by seangates** [comment]
Yes, let's port this fix to 8 to make sure everything is right. Thanks!

**Pull request merged**
