### PR TITLE
DS6.5 button updates

### PR DESCRIPTION
**Pull request by msendlakowski**
## Description
- Update button styles for DS6.5
- Remove support for "regular", "medium" and "extra-large" on DS6.  Regular, medium, and extra-large will now all fallback to the default DS6 size, which is large.
- Support "small" button for DS6. 
- Add "delete" style for secondary buttons. (DS6 only)
- Remove "legacy" style from DS6.
- Fix hover/focus state for disabled primary links in DS6

## Context
This is a sync up with the latest DS6.5 styles.

I also updated the fixed-height and truncated demos to use small and large sizes, rather than medium, since medium is no longer supported on DS6.5.

## References
Closes https://github.com/eBay/skin/issues/700

## Screenshots
Screen Shot 2019-08-07 at 3 11 23 PM
Screen Shot 2019-08-07 at 3 11 36 PM
Screen Shot 2019-08-07 at 3 11 46 PM
Screen Shot 2019-08-07 at 3 11 55 PM

### CODE REVIEW

**Comment by seangates** [comment]
Is the assumption that all buttons are "large"? At least, that's what I'm seeing?

**Comment by seangates** [comment]
E.g. I was expecting to see a `button.btn--large`, but I only see that as part of the "legacy" you kept for fixed height and truncated buttons.

**Comment by msendlakowski** [comment]
There is no more medium button.  And large is the recommendation for mweb, so I chose that as the default.  All legacy medium and extra-large will default to large now.

I kept large for fixed height and truncated because of the old naming convention `btn--large-truncated`.  Its still supported in skin for DS4 so I figured we had to support it in DS6 for now.

Since this is a major version update, I could change it so user's would have to set the size and variant separately.  Like `btn--small btn--truncated`.

**Comment by seangates** [comment]
So, dWeb will have to be explicit and call their button `btn--small`?

**Comment by msendlakowski** [comment]
> So, dWeb will have to be explicit and call their button `btn--small`?

We have to make a choice.  Either we use small as default and dweb has to specify `btn--large`, or we use large as default and they have to specify `btn--small`.

**Comment by msendlakowski** [comment]
> As for the default size. There was the concept of a "raw" button, which just used the browser's default height for buttons. A size modifier always had to be added.

The height is still determined, as 40px, but based on font size and padding, both specified by skin. So the new default made it 48.  

My concern with removing features from DS4 is that I thought we promised that DS4 designs won't change when applications adopt ebayUI.  I'd like to talk to you offline about this.

**Comment by msendlakowski** [comment]
Closing. Going to rework this.

**Comment by ianmcburnie** [comment]
We have to make the DS4 and DS6 API the same as we move towards one design. @seangates and I have been slowly closing the gap over the last 18 months or so and are almost there. Teams that are on really old versions of DS4 are not likely to be updating any time soon, and if they do they should be moving forward with v8 then v9.

**Pull request closed without merging**
