### PR TITLE
Removed :hover for touch devices like iPad

### PR DESCRIPTION
**Pull request by agliga**
## Description
On Ipad there is an issue when clicking on a link in a carousel it focuses on paddles first. So user has to double click. Thi sis an Ipad issue
Removed `:hover` when not on `@media hover` devices

## References
https://github.com/eBay/ebayui-core/issues/1251

### CODE REVIEW

**Review by ianmcburnie — COMMENTED** [review]
Just checking on those pesky `docs.min.js` files. Not sure if that's intentional or not?

**Comment by agliga** [comment]
> Just checking on those pesky `docs.min.js` files. Not sure if that's intentional or not?

Reran build, was due to switching between `11.0.0` and this. 
Might want to figure out something to prevent those from getting checked in

**Comment by ianmcburnie** [comment]
Little githook to run yarn when switching branches maybe?

**Review by ianmcburnie — COMMENTED** [review]
Could this cause any issue for (bluetooth) keyboard users?

**Comment by agliga** [comment]
> Could this cause any issue for (bluetooth) keyboard users?

Not sure what you mean by bluetooth keyboard users (Ipad with a keyboard?). 
However `:focus` still works, so you can still tab through and see the paddles on a device.

**Comment by ianmcburnie** [comment]
Yep, iPad with a keyboard. It's a thing :-)

Anyway, so long as user can tab through and still see paddles, we are good.

**Review by ianmcburnie — APPROVED** [review]
Might be worth getting a 2nd look from Dylan too.

**Comment by ianmcburnie** [comment]
Let's merge and release.

**Pull request merged**
