### PR TITLE
Fix dialog display issues.

### PR DESCRIPTION
**Pull request by DylanPiercey**
## Description
This PR fixes the scrollbar issues in the dialog on various browsers.
It does this by removing the `dialog__mask` element and putting the mask directly as a background on the dialog itself. The modifiers for the `dialog__mask` have been moved to the dialog itself as well. For example `dialog__mask--fade` is now `dialog--mask-fade`.

It also changes from using `margin-bottom` on the window (switching to padding), which fixes an issue in safari where the 15vh bottom padding for fill and normal dialogs was not respected.

## References
This PR addresses https://github.com/eBay/ebayui-core/issues/105 and https://github.com/eBay/ebayui-core/issues/106.

### CODE REVIEW

**Comment by ianmcburnie** [comment]
@DylanPiercey Is this change for all flavors of the dialog? Or just the full dialog? How did you get around the staggered transition requirement of dialog background and foreground that we discussed?

**Comment by DylanPiercey** [comment]
This fixes all flavors of dialog. For staggered transitions I just changed the modifier for the mask to be on the `.dialog` itself and am transitioning the background-color, which is now rgba.

**Comment by ianmcburnie** [comment]
@DylanPiercey Nice! How is browser support for transitioning the alpha channel?

I remember in DS4 we had to use opacity, but of course because child elements always inherit the opacity of their parents, we had to have the mask as a separate element in order to support staggered transitions.

I am very excited if we can finally ditch the mask! :-)

**Comment by DylanPiercey** [comment]
Should be ie9 and up 😁. https://caniuse.com/#feat=css3-colors

**Pull request merged**
