### PR TITLE
Add storybook

### PR DESCRIPTION
**Pull request by raveenakothapally**

### CODE REVIEW

**Comment by raveenakothapally** [comment]
> Looking good. One thing I notice though is that the RTL examples are not displaying correctly. The attribute `dir=rtl` will need adding to an ancestor element of the module.

Done

**Comment by raveenakothapally** [comment]
> I think this is looking great. I'll probably also go back through and cleanup/rename some tests after they've all been ported over from their existing format. Thanks!

Sure :)

**Comment by ianmcburnie** [comment]
I'll also wait for @agliga to have a scan through. Especially related to the image/svg script.

**Comment by raveenakothapally** [comment]
> I'll also wait for @agliga to have a scan through. Especially related to the image/svg script.

Sure, I am doing a new PR for few other cases

**Pull request merged**
